### PR TITLE
Remove head dependencies

### LINKED ISSUE #4673: Remove :head dependency declaration
The `:head` dependency declaration allows to use the last published podspec with the current source code in the repo. That could be easily an untested configuration, if there were structural changes to the pod. The behavior of that declaration isn't quite obvious and easily leads to the misconception that it would use also the latest version of the podspec.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4673.
Depends upon https://github.com/CocoaPods/Core/pull/286.

@CocoaPods/core made a separate PR for this since this is a huge change. Please everyone :+1:  or :-1: this change.

### CODE REVIEW

**Comment by mrackwitz** [comment]
:fire: :+1: But I thought that this decision made. There was no one so far raising voice against this change.

**Comment by orta** [comment]
:+1: - figure this is just to make that agreement public, we discussed it in our slack rather than an issue

**Comment by neonichu** [comment]
:+1:

**Comment by manuyavuz** [comment]
:+1:

**Pull request merged**
