### PR TITLE
[TargetIntegrator] Remove embed frameworks build phase where not needed

### PR DESCRIPTION
**Pull request by mrackwitz**
Fixes issues like #3905.
* [x] CHANGELOG

### CODE REVIEW

**Comment by segiddins** [comment]
No point doing this when my PR will just add them back, given they'd be shipped in the same release?

**Comment by mrackwitz** [comment]
No, your PR would just add them when integrating with static libraries for apps and tests. This ensures they are removed e.g. for extensions. This shouldn't be conflicting.

**Comment by segiddins** [comment]
Gotcha.

**Comment by segiddins** [comment]
This will conflict git-wise with my PR, but that's my fault for it being open so long. :+1: excellent work @mrackwitz !

**Pull request merged**
