### PR TITLE
[Installer] Delay source file locking

### LINKED ISSUE #3529: Post-install hook: Permission denied
We have a post-install step which removes AFNetworkings UIImageView category:
```ruby
    pod.source_files.each do |pathname|
        if pathname.to_s.include? "/AFNetworking/UIImageView"
            File.open(pathname, 'w').write("/* REMOVED USE SDWEBIMAGE INSTEAD */")
        end
    end
```

As of 0.37 (0.37.0 and 0.37.1) this no longer works:
```
Permission denied - /PATH_TO_APP/Pods/AFNetworking/AFNetworking/UIImageView+AFNetworking.h
```

### PR DESCRIPTION
**Pull request by segiddins**
Also, make sure to unlock the sandbox when preparing the sandbox

Closes #3529

### CODE REVIEW

**Comment by neonichu** [comment]
Any reasons why we're switching to shelling out by using FileUtils?

**Comment by segiddins** [comment]
@neonichu it's clearer what's happening than doing the bit mask math ourselves

**Comment by neonichu** [comment]
:+1:

**Comment by alloy** [comment]
Kewl :+1:

**Pull request merged**
