### PR TITLE
prepended $(inherited) to OTHER_LDFLAGS and HEADER_SEARCH_PATHS to the generated xcconfig

### PR DESCRIPTION
**Pull request by patcheng**
that way, settings from Project level in xcodeproj could be inherited.

### CODE REVIEW

**Comment by patcheng** [comment]
it has the same change for OTHER_LDFLAGS as PR https://github.com/CocoaPods/CocoaPods/pull/2971

Looks like the issue is mentioned in issue https://github.com/CocoaPods/CocoaPods/issues/546 and https://github.com/CocoaPods/CocoaPods/issues/2467

**Comment by segiddins** [comment]
@samdmarshall can you think of any reason not to add `$(inherited)` to `OTHER_LDFLAGS` / `HEADER_SEARCH_PATHS`?

**Comment by segiddins** [comment]
Can confirm that the only failures are expected changes to the integration specs.

**Comment by samdmarshall** [comment]
I don't think there is any reason not to add it.

**Comment by hypotamtam** [comment]
When do you think that it will be release?

**Pull request merged**
