### PR TITLE
Improve 1.0 error messages around not-found dependencies

### PR DESCRIPTION
**Pull request by orta**
The majority of the discussion is in #5135 - for now this will handle the implementation aspects

### CODE REVIEW

**Comment by orta** [comment]
Is this worth adding a changelog entry?

**Comment by segiddins** [comment]
@orta, yes an entry under enhancements is called for since its closing an issue.

**Comment by orta** [comment]
Done'd :+1:

**Comment by segiddins** [comment]
You also need to update the tests :P

**Comment by orta** [comment]
Hah - so I can, and have fixed one of the tests, but the other is the example where it appears twice, any thoughts on what the logic should look like to only show it once if it's `Podfile` & `Podfile.lock`?

```
- `Nimble-Snapshots` required by `Podfile`
- `Nimble-Snapshots (= 4.0.0)` required by `Podfile.lock`
```

```
None of the spec sources contain a spec satisfying the `Nimble-Snapshots` dependency.
You have either; mistyped the name or version, not added the source repo that hosts the Podspec to your Podfile, or not got the latest versions of your source repos.

None of the spec sources contain a spec satisfying the `Nimble-Snapshots (= 4.0.0)` dependency.
You have either; mistyped the name or version, not added the source repo that hosts the Podspec to your Podfile, or not got the latest versions of your source repos.
```

**Comment by orta** [comment]
Or not, was just some dodgy string interpolation 🎉 - though that problem still remains

**Comment by alloy** [comment]
👍

**Pull request merged**
