### PR TITLE
Update fourflusher version

### PR DESCRIPTION
**Pull request by dnkoutso**
Due to release for https://github.com/CocoaPods/CocoaPods/issues/8458

### CODE REVIEW

**Comment by dnkoutso** [comment]
Pointed this to `1-6-stable`. Its a minor update that prepares for Xcode 10.2 beta.

**Comment by dnkoutso** [comment]
I mostly agree. This was going to be done as part of the release script automatically for `fourflusher` which it would not include such requested `CHANGELOG`. I will add manually.

**Comment by dnkoutso** [comment]
actually @amorde this would require merging the `CHANGELOG` in master..........I am sorry I am going to merge as is.

**Comment by amorde** [comment]
no worries 👍

**Pull request merged**
