### PR TITLE
:sparkles: :tada: [fish] tab-completion support 

### PR DESCRIPTION
**Pull request by archmagees**
Add the tab-completion support for fish shell. 🎉

### CODE REVIEW

**Comment by orta** [comment]
This is great, how do people use it?

**Comment by dnkoutso** [comment]
I think you have to use http://fishshell.com/ ?

**Comment by orta** [comment]
I'm a fish user 👍, but I don't see anything that would get shipped with the gem for example - so I'm interested in how anyone wanting to use this could get it all hooked up

**Comment by archmagees** [comment]
@orta 
You just need to link it to the following directories:
```shell
cat $fish_complete_path
```
Just pick a directory, and put `pod.fish` in it.
Then you can enjoy the tab-completion for CocoaPods in fish shell.

**Comment by dnkoutso** [comment]
LGTM. Don't know much but it seems like it works :)

**Comment by segiddins** [comment]
This should probably be integrated into https://github.com/CocoaPods/claide-completion, since we try to avoid bundling auto-complete definitions directly into CocoaPods, since they require maintenance

**Comment by amorde** [comment]
@archmagees interested in submitting this to https://github.com/CocoaPods/claide-completion? since these files won't ship with the gem, it's not easy for end users to install, and as mentioned above we'd prefer to keep shell completions out of this repo for easier maintenance

**Comment by dnkoutso** [comment]
Closing for inactivity.

**Pull request closed without merging**
