### PR TITLE
Make copy resources echoes always return true

### PR DESCRIPTION
**Pull request by dnkoutso**
/cc @postmechanical

### CODE REVIEW

**Comment by postmechanical** [comment]
:shipit: 🤷‍♂️

**Comment by dnkoutso** [comment]
@postmechanical there we go. Now its green.

**Comment by postmechanical** [comment]
@dnkoutso So you don't care about CircleCI build?

**Comment by dnkoutso** [comment]
@postmechanical not right now its work in progress. It's not required to merge

**Comment by dnkoutso** [comment]
@DanToml LGTY?

**Comment by dnkoutso** [comment]
rebased.

**Pull request merged**
