### PR TITLE
Fix: just return the "path" when calling "binary_path" on XCFramework Slice when it is a library

### LINKED ISSUE #10165: Incorrect OTHER_LDFLAGS for xcframeworks containing static binaries (beginning 1.10.0 release)
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Project setup:
An iOS app that consumes a development pod that has two vendored_frameworks that are both xcframeworks (both using static binaries)

The xcframeworks both have the same naming convention, so i'll provide one for simplicity.

File tree structure of example xcframework

Whats wrong? Beginning with cocapods v1.10.0, the ./Pods/Target Support Files/TheDevelopmentPodTarget/TheDevelopmentPodTarget.{release|debug}.xcconfig has an incorrectly generated `OTHER_LDFLAGS`. They were correct in cocapods v1.10.0.rc.1

What is the correct (previous) outcome under v1.10.0.rc.1:
`OTHER_LDFLAGS = $(inherited) -l"MYXCFramework-iOS-XX-1.35.0" -l"MYOtherXCFramework-iOS-XX-1.35.0" -l"c++" -framework "CoreBluetooth" -framework "UIKit"`

What is the current (wrong) outcome under v1.10.0:
`OTHER_LDFLAGS = $(inherited) -l"mYXCFramework-iOS-XX-1.35" -l"mYOtherXCFramework-iOS-XX-1.35" -l"c++" -framework "CoreBluetooth" -framework "UIKit"`

Note that the name of the xcframework was incorrectly changed (case change and clipping of version number) `MYXCFramework-iOS-XX-1.35.0` vs `mYXCFramework-iOS-XX-1.35`

As a result, trying to compile the app fails as the library was not linked (since the name was incorrect). Locally changing the name to the correct name of the xcframework fixes the issue and the app compiles and runs.

## What did you expect to happen?
Correct Result (as was seen in v1.10.0.rc.1):
`OTHER_LDFLAGS = $(inherited) -l"MYXCFramework-iOS-XX-1.35.0" -l"MYOtherXCFramework-iOS-XX-1.35.0" -l"c++" -framework "CoreBluetooth" -framework "UIKit"`

## What happened instead?
Incorrect Result (as seen in v1.10.0)
`OTHER_LDFLAGS = $(inherited) -l"mYXCFramework-iOS-XX-1.35" -l"mYOtherXCFramework-iOS-XX-1.35" -l"c++" -framework "CoreBluetooth" -framework "UIKit"`

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d5ef74c789dcf2f7641574c16b73fa7b22f22770

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins
```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
slather               : 2.5.0
```

## Project that demonstrates the issue
I'd love to make a sample project, but I cannot find any publicly available xcframeworks that use static libraries. If you know of a sample project let me know and I'll make a sample project.

### PR DESCRIPTION
**Pull request by Westacular**
closes #10165

It was simpler to just fix `binary_path` and not make any changes in build_settings (i.e. to call `path` as I'd previously suggested [here](https://github.com/CocoaPods/CocoaPods/issues/10165#issuecomment-755636178)), because various unit tests _only_ mock `binary_path`.

The relevant integration test will need updating; I'll push a PR with the fix for that momentarily.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix: just return the "path" when calling "binary_path" on XCFramework Slice when it is a library  
  [Westacular](https://github.com/Westacular)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Is there a test we can add?

**Comment by dnkoutso** [comment]
Ah looks like some integration specs also need updating.

**Comment by Westacular** [comment]
> Ah looks like some integration specs also need updating.

Just pushed https://github.com/CocoaPods/cocoapods-integration-specs/pull/307

**Comment by amorde** [comment]
@Westacular I pushed up some extra unit tests for you, hope you don't mind

**Comment by dnkoutso** [comment]
@Westacular I also merged the integration specs PR, feel free to bump them here and I think your pR will go green and we can merge it.

**Comment by Westacular** [comment]
@amorde Don't mind at all! Thanks.

@dnkoutso I've bumped the integrations specs ref

**Pull request merged**
