### PR TITLE
 [Resolver] Fix multi-source resolution

### LINKED ISSUE #7031: Two different sources providing the same pod yields wrong resolved version
This is a link to https://github.com/CocoaPods/Molinillo/issues/88.

The summary is that the resolution of a pod that exists in at least two sources does not resolve properly.

It is unknown whether the bug is in the integration of CocoaPods and Molinillo 0.6.x or in Molinillo itself.

I am filing this issue in this project because an outside consumer of CocoaPods will not get the behavior expected when using CocoaPods master (or 1.4.x when it ships).

### PR DESCRIPTION
**Pull request by segiddins**
Closes #7031 by ensuring that specs are properly ordered by both version _and_ source preference.
Mostly took so long because I had to build out the test infrastructure to be able to reproduce the issue without live git repos.

cc @justinseanmartin

### CODE REVIEW

**Comment by dnkoutso** [comment]
Let's ship this with 1.4.0.

**Comment by valeriomazzeo** [comment]
Has this been fixed for `pod lib lint --sources` as well?

It doesn't seem to respect the order of sources, when `MyPod` exists in both a private repo and the master repo with the same name and similar versions.

`pod lib lint --allow-warnings --private --fail-fast --sources=git@github.com:myorg/cocoapods-specs.git,https://github.com/CocoaPods/Specs.git`

Podspec: `spec.dependency 'MyPod', '~> 1.0.0'` picks up the pod from master
Podspec: `spec.dependency 'MyPod', '1.0.0'` picks up the pod from the private repo

**Comment by segiddins** [comment]
If the one in the master repo has a higher version, then that’s the intended behavior

**Comment by valeriomazzeo** [comment]
I see.

What would be the use case scenario for that behaviour?

At the moment, I have a private pod which has a name collision with a public one, but I just want to use mine. I find difficult to find a case where I would want to override a public pod, in a private source, and then dynamically switch from one to the other based on the version.

In my opinion, when multiple reference are found, it would make more sense to stick to the pod available in the first source that contains a pod with that name, regardless of the version definition.

**Pull request merged**
