### PR TITLE
For fix slow dependency issue(base on 1.0.0).

### PR DESCRIPTION
**Pull request by yanzhiwei147**
for issue #5180

### CODE REVIEW

**Comment by manuyavuz** [comment]
@yanzhiwei147,

As @segiddins said before, we need to see some results showing the performance gain coming with your change.

You can use [Benchmark Module](http://ruby-doc.org/stdlib-2.0.0/libdoc/benchmark/rdoc/Benchmark.html) to run some tests and add results here.

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><p>Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</p>
</td>
    </tr>
    
    
  </tbody>
</table>
  

  

  



Here's an example of your CHANGELOG entry:

```markdown
* For fix slow dependency issue(base on 1.0.0). 
  [yanzhiwei147](https://github.com/yanzhiwei147)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by yanzhiwei147** [comment]
@manuyavuz It's enough only provide the total time for `pod update`?

**Comment by manuyavuz** [comment]
Yes, because the main problem is `pod update`, showing results with and without caching would be enough

**Comment by yanzhiwei147** [comment]
The performance report is here(need make PR to `Cocoapods Core` same time):
- Make a `Ruby` script, it has follow content:
```ruby
require 'benchmark'

Benchmark.bm do |x|
  x.report { `pod update --no-repo-update`}
end
``` 
- Install cocoapods of version 1.0.1
- Test origin program performance, and get result
```sh
$ ruby time.rb                                              
       user     system      total        real
  0.000000   0.000000 27773.300000 (28141.220305)
```
- Test the PR program performance, and get result
```sh
$ ruby time.rb                                              
       user     system      total        real
  0.000000   0.000000 827.470000 (827.948731)
```

---
 The  `Podfile` conent
```ruby
# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.sdp.nd/cocoapods/spec.git'

platform :ios, '7.0'

project 'test_demo'

abstract_target 'factory' do

    target 'share0' do
        pod 'ShareAppExtension', '1.0.57'

 post_install do |installer_representation|
     installer_representation.pods_project.targets.each do |target|
         if target.name == "AFNetworking"
             target.build_configurations.each do |config|
                 puts "Setting AF_APP_EXTENSIONS macro in config: #{config}"
                 config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
             end
         end
     end
 end
    end

    target 'test_demo' do
        podspec :path => 'new99u2/Resources/skin/SDPSkinImport.podspec'
    podspec :path => 'new99u2/Resources/i18n/SDPLanguageImport.podspec'
    # pod 'UCComponent'
    #pod 'APFKit'
    pod 'MUIKit'
    # pod 'APFMainComponent'
    pod 'MUPFoundation'
    pod 'BlocksKit'

    #com.nd.sdp:uc_component:release

            
            pod 'UCComponent', '0.2.115'
pod 'UCSDK','0.10.82'
pod 'VirtualOrgSDK','1.0.25'
pod 'UCExtend', '0.2.31'
pod 'ContentServiceSDK', '0.2.55'
pod 'CephS3SDK','1.4.1'
             
        

    #com.nd.smartcan.appfactory:main_component:release

            
                pod 'APFMainComponent', '0.2.79'
                pod 'APFKit', '0.1.87'
pod 'MUPFoundationNetworking', '1.0.15'
pod 'SmartCan', '0.5.33'
pod 'APFWebKit', '1.0.33'
pod 'SMCDataLayer', '0.4.19'
pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end
            
        

    #com.nd.social:backpack:release

            
                pod 'BackpackComponent', '6.7.1'
            
         

    #com.nd.social:im:release

            
                pod 'IMSComponent', '6.9.2'
                pod 'IMSDK' , '6.9.3'
                pod 'RATreeView', :git => 'https://github.com/kukushi/RATreeView.git', :commit => 'a4c96cb38bcd95f405b26d59363add1bd397d846' 
               
        

    #com.nd.social:voting:release

            
            pod 'VotingComponent', '0.2.34'
             
        

    #com.nd.social:notice:release

            
            pod 'NoticeComponent', '0.3.45'
             
        

    #com.nd.social:appbox:release

                    
                        pod 'AppBoxComponent','7.0.2'
                    
                

    #com.nd.social:weibo:release

                    
                        pod 'MicroBlogComponent','7.0.0'
                    
                

    #com.nd.social:lottery:release

            
                pod 'LotteryComponent', '6.8.1'
            
         

    #com.nd.social:appsetting:release

                    
                        pod 'AppSettingComponent','6.9.2'
                    
                

    #com.nd.social:flower:release

              
                      pod 'SendFlowerComponent', '6.7.2'
             
             

    #com.nd.social:ERP:release

             
                pod 'ERPComponent','0.6.42-TEST'
                pod 'ERPCommonLib','0.5.7'
                pod 'ERPCommonUIModule','0.5.3'
            
        

    #com.nd.social:birthdaywishes:release

            
                pod 'BirthdayWishesComponent', '0.4.6'
               
        

    #com.nd.social:me:release

                    
                        pod 'MeComponent','7.0.0'
                    
                

    #com.nd.social:greenhandguide:release

                    
                        pod 'GreenHandGuideComponent','0.1.8'
                    
                

    #com.nd.social:netdisk:release

           pod 'YunPanComponent', '0.4.19'
        

    #com.nd.sdp:common_skin_component:release

            
               pod 'CommonSkinComponent', ' 1.2.10'
             
        

    #com.nd.social:forum:release

              
                      pod 'ForumComponent', '7.0.0'
                      pod 'RATreeView', :git => 'https://github.com/kukushi/RATreeView.git', :commit => 'a4c96cb38bcd95f405b26d59363add1bd397d846' 
             
             

    #com.nd.social:news:release

            
                      pod 'NewsComponent', '7.0.0'

        

    #com.nd.erp:employee:release

                   
                      pod 'ProfileComponent', '0.2.14'
                   
                 

    #com.nd.erp:esop:release

                 
                    pod 'ESOPComponent', '0.0.23'
                 
             

    #com.nd.erp:violation:release


    #com.nd.erp:atnd:release

                    
                        pod 'ATNDComponent','0.2.13'
                    
          

    #com.nd.social:qr-code:release

            
            pod 'QRCodeComponent', '0.2.17'
             
        

    #com.nd.social:activity:release

                     
                     pod 'ActivityComponent','7.0.2'
                     
                

    #com.nd.hy:elearning:release

            
                pod 'elearn_mutualcomponent', '1.0.132'
                pod 'elearning2', '3.5.38'
                pod 'open_courses_ios', '3.5.19'
                pod 'elearn_assessment', '1.0.59'
             
        

    #com.nd.sdp:data_analysis_component:release

            
                pod 'DAComponent', '1.0.12'   
             
        

    #com.nd.erp:goods:release


    #com.nd.sdp.component:crashreport:release


    #com.nd.social:lbs:release

            
           pod 'LBSComponent', '0.0.40'
             
        

    #com.nd.social:vote:release

            
            pod 'VoteComponent', '6.6.0'
             
        

    #com.nd.oa:improve-info:release

            
            pod 'ImproveInfoComponent', '0.0.51'
             
        

    #com.nd.social:cloudalbum:release

            
              pod 'CloudPhotoAlbumComponent', '0.1.17'
             
        

    #com.nd.social:donatecomponent:release

            
                  pod 'SocialDonateComponent', '6.8.1'
             
        

    #com.nd.social:collection:release

            
            pod 'CollectionComponent', '0.4.10'
             
        

    #com.nd.cloudoffice:sign:release

            
             pod 'CloudSignInComponent', '1.1.61'
             
        

    #com.nd.cloud:cloud-db:release

             
             pod 'CloudDataComponent','1.0.0'
             
        

    #com.nd.social:emotionmall:release

            
                pod 'MUIExpressionMallComponent', '0.0.18'
             
        

    #com.nd.sdp.component.cloudatlas:cloud-atlas-component-bussiness:release

         
            pod 'cloudatlas_ios_component', '0.7.2'
          
        

    #com.nd.social:videoconference:release

            
            pod 'VideoConferenceComponent', '6.8.7'
            pod 'JuphoonSDK', '6.8.0'
              
        

    #com.nd.cloudoffice:announcement:release

            
             # pod 'AnnouncementComponent'
             
        

    #com.nd.erp:todo:release

            
                 pod 'ToDoComponent', '0.0.13'
             
        

    #com.nd.social:appextention:release


    #com.nd.erp:myhabit:release

            
               pod 'MyHabitComponent', '0.0.22-TEST'
             
        

    #com.nd.social:socialshop:release

            
                pod 'SocialShopComponent', '7.0.1'
    end
end 
```

**Pull request closed without merging**
