### PR TITLE
Fix project path handling issue causing bad cmake generated projects

### LINKED ISSUE #6268: (cocoapods 1.1.1) pod install on a project generated by cmake results in broken xcconfig file references
# Report

## What did you do?
Run the following commands on the attached project:
* Note that the python (2.7.x) script works around another bug that makes cocoapods fail when used with cmake generated projects.
* Note2: cmake version 3.7.1 was used.

```
 # assuming you're in a bash terminal and cd'd into the directory into which the attached
 # project was extracted.
 cd bin
 cmake ../HelloCocoaPods/ -GXcode
 python ../HelloCocoaPods/fix_pbxproj.py --input HelloCocoaPods.xcodeproj/project.pbxproj 
 pod install
 open HelloCocoaPods.xcworkspace/
 # Now, when in Xcode, compile the project (Xcode 8.1 was used)
```

## What did you expect to happen?
xcconfig references are valid and project compiles successfully.

## What happened instead?
Compilation error:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0ec2ec9dbf40a5353198ab3aa307644a0b217579
```

### Installation Source

```
Executable Path: /[redacted]/rubygems/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :osx, '10.11' 


target "HelloCocoaPods" do
   pod 'Fabric'
end
```

## Project that demonstrates the issue
[CocoapodsCMakeBugReproductionProject.zip]
(https://github.com/CocoaPods/CocoaPods/files/629579/CocoapodsCMakeBugReproductionProject.zip)

### PR DESCRIPTION
**Pull request by paulb777**
Fix #6268 

Follows on #8355 with unit tests.

This PR depends on https://github.com/CocoaPods/Xcodeproj/pull/739

### CODE REVIEW

**Comment by dnkoutso** [comment]
is there a test you can add that fails now until you bump Xcodeproj in the Gemfile?

**Comment by paulb777** [comment]
There should be. I'll need to do a bit more investigation to find it and I'll follow up next week.

**Comment by paulb777** [comment]
nvm, I found one today. :)

**Comment by dnkoutso** [comment]
@paulb777 sorry again needs a rebase due to 1.9.1 release.

**Comment by dnkoutso** [comment]
just `bundle exec rubocop -a` and its good!

**Pull request merged**
