### PR TITLE
[Gemspec] Bump ruby-macho to '~> 2.1'

### PR DESCRIPTION
**Pull request by woodruffw**
See https://github.com/Homebrew/ruby-macho/pull/113 and https://github.com/Homebrew/ruby-macho/pull/114.

### CODE REVIEW

**Comment by dnkoutso** [comment]
Seems like this does not work in CI:
```
ruby-macho-2.1.0 requires ruby version >= 2.2, which is incompatible with the
current version, ruby 2.0.0p647
```

@segiddins @DanToml is 2.0.0 of Ruby required to be tested?

**Comment by segiddins** [comment]
Yes, CocoaPods still supports ruby 2.0.0

**Comment by dnkoutso** [comment]
@woodruffw is it easy to cherry-pick this your fix in the 1.x release?

**Comment by shekhar-suman** [comment]
@woodruffw Thanks for working on this issue. Can we please merge this soon. Xcode 10 is already out and this is breaking our build.

**Comment by amorde** [comment]
@shekhar-suman you can use [Bundler](https://bundler.io/) to pull in the version of `ruby-macho` you need if this is a blocker for you

**Comment by shekhar-suman** [comment]
@amorde I do have latest ruby-macho and it works fine if used standalone. My problem is with Cocoapod as it is still dependent and using older version of ruby-macho. Hence my 'pod install' is failing. It can not use a vendored_framework for a framework which has arm64_32 arch.

**Comment by woodruffw** [comment]
@shekhar-suman For a temporary fix, you can always modify your local copy of CocoaPods (I don't know anything about how CocoaPods is installed, but if it's anything like Homebrew you can just check this branch out and run `bundle install`). Similarly, unless you're actually using that `arm64_32` slice, you can always temporarily disable it in your build.

@dnkoutso Probably not, since there were additional changes in the 1.x tree that are marked as non-2.0 compatible. However, as I mentioned in https://github.com/CocoaPods/CocoaPods/pull/7815, the library *probably* still works on 2.0, I just don't have a CI setup to test it on 2.0 anymore. I'll look at tweaking the Ci to remedy that.

**Comment by woodruffw** [comment]
Tried applying some hacks to bring things back down to 2.0 in https://github.com/Homebrew/ruby-macho/pull/115, but the library's changed a bit more than I was aware (since I usually develop on the latest ruby and let the CI sort things out). In particular, ruby-macho currently makes use the `String#+@` operator for unfreezing literals and uses `Integer#negative?` in a few places, both of which didn't appear until Ruby 2.3.

macOS 10.13 and higher supply at least Ruby 2.3, which would work just fine; would it be possible for CocoaPods to do something similar to Homebrew and use a vendored Ruby version on older system versions?

**Comment by segiddins** [comment]
CocoaPods always supports back 2 OS X / Xcode versions and is installed as a gem, so vendoring an older ruby version isn’t possible

**Comment by woodruffw** [comment]
I've made one last Ruby 2.0/2.1/2.2 compatible release, containing all of the feature additions and bug fixes from the latest (incompatible) release.

**Comment by segiddins** [comment]
Thanks!

**Pull request merged**
