### PR TITLE
Make de-integration wording less verbose.

### LINKED ISSUE #4718: Have de-integration less verbose during migration?
Perhaps this section could just be:

```
Re-creating CocoaPods due to CocoaPods major version update.
````

from:

```
Fully deintegrating due to major version update

Deintegrating `CocoaPods.xcodeproj`
Deintegrating target `CocoaPods`
Deintegrating target `pod`
Deintegrating target `CocoaPodsTests`
Deintegrating target `ReflectionService`
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
```

### PR DESCRIPTION
**Pull request by DarrylBayliss**
Closes #4718

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻
@orta thoughts on the message change?

**Comment by orta** [comment]
Perfect, thanks @DarrylBayliss

**Comment by alloy** [comment]
I just ran into this one, I think neither of the messages are helpful or needed.

As it stands, I just get to see this and have no clue what it means or what I should do with that information.

```
Re-creating CocoaPods due to major version update.
```

**Comment by alloy** [comment]
@segiddins Remind me, is there a way to log sections only in verbose mode?

**Comment by segiddins** [comment]
@alloy `UI.notice` I believe, but check the docs or the source

**Pull request merged**
