### PR TITLE
Skip the "install_framework" step for "Debug" configuration

### PR DESCRIPTION
**Pull request by icecrystal23**
The "install_framework" step is not necessary for running Debug builds.  Skipping this script in "Debug" configuration saves us a lot of time when running Debug builds, as we have a lot of frameworks included.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Skip the "install_framework" step for "Debug" configuration  
  [icecrystal23](https://github.com/icecrystal23)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
>The "install_framework" step is not necessary for running Debug builds.

I don't think that is true, why do you think that is the case?

**Comment by icecrystal23** [comment]
> > The "install_framework" step is not necessary for running Debug builds.
> 
> I don't think that is true, why do you think that is the case?

Because there is nothing inherently wrong with fat frameworks.  They work fine on both devices and simulators.  Apple complains about them when you upload (they don't want you shipping simulator code), which is why it is necessary to strip out the simulator code before uploading a release build.

**Comment by dnkoutso** [comment]
If pods are built as frameworks they need to be copied over to the app bundle so they can be loaded. I do not see how that works if we dont copy them.

**Comment by icecrystal23** [comment]
I thought the script was only doing the stripping; now I see it is actually doing the copying too.  I thought the stripping was what was taking so long, but it only saves 1 second off our builds to skip stripping (takes 9 seconds to do the copy and 10 if we copy and strip 😞).  Oh well.

**Pull request closed without merging**
