### PR TITLE
Fixes path issues with CMake generated projects

### PR DESCRIPTION
**Pull request by mad-rain**
Hi!

Please see https://github.com/CocoaPods/CocoaPods/issues/6268 for more info.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fixes path issues with CMake generated projects  
  [mad-rain](https://github.com/mad-rain)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by segiddins** [comment]
Please add a test and a changelog entry for this fix, thanks!

**Comment by dnkoutso** [comment]
@mad-rain ping on this want to finish it?

**Comment by dnkoutso** [comment]
@mad-rain ping again.

**Comment by mad-rain** [comment]
@dnkoutso Unfortunately I have limited time to spend on this issue and I have zero Ruby experience. Any help is appreciated!

**Comment by dnkoutso** [comment]
Closing stale PRs.

**Comment by paulb777** [comment]
Continued in #9551

**Pull request closed without merging**
