### PR TITLE
Replace Open4 with systemu

### LINKED ISSUE #3101: pod install doesn't seem to recognize pull is complete.
I'm running pod install. We have both CocoaPods Spec and an internal repository. pod doesn't seem to know that the spec is fully pulled, and sits waiting for that to be noticed.

```bash
[~]$ git --version
git version 2.2.2
[~]$ pod --version
0.35.0
[~]$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

When I hit Control-C, the stack for waiting is below. When I cd in ~/.cocoapods/repos, I see both the the specs available. When I cd into Pods/podmodule/ I see it is available. It seems that pod is not noticing that the git operation is complete:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:68:in `block in wait': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:66:in `wait'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:196:in `block (2 levels) in pop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:188:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:188:in `block in pop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:187:in `handle_interrupt'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:187:in `pop'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:206:in `block in all_done'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:206:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:206:in `all_done'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:199:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:358:in `block (3 levels) in spawn'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:111:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:111:in `do_popen'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:46:in `popen4ext'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:336:in `block (2 levels) in spawn'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:335:in `block in spawn'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:374:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:374:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:334:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/executable.rb:66:in `execute_command'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:12:in `execute_command'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:152:in `block in executable'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:65:in `block in clone'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:45:in `block in ui_sub_action'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:44:in `ui_sub_action'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:63:in `clone'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:29:in `download!'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:29:in `block in ui_action'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:28:in `ui_action'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:78:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:98:in `download_source'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:45:in `install!'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:298:in `install_source_of_pod'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:273:in `block (2 levels) in install_pod_sources'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:272:in `block in install_pod_sources'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `install_pod_sources'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:116:in `block in download_dependencies'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:114:in `download_dependencies'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:91:in `install!'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by cbrauchli**
Replace Open4 with systemu. From #3101, it looks like multiple people have experienced this. I myself have experienced this on multiple computers, configured very similarly. I can't find anything deterministic about it. Reading online, it looks like other people have experiences similar issue with Open4 and it seems to be related to handling STDOUT and STDERR with it.

Closes #3101.

### CODE REVIEW

**Comment by segiddins** [comment]
This change isn't mergable, because it goes back to executing commands with a string instead of an array. I'd rather fix open4, could you point me in the direction of what exactly it's doing wrong?

**Comment by cbrauchli** [comment]
I'm honestly not sure what exactly it's doing wrong. There's this issue https://github.com/ahoward/open4/issues/7 where the author suggests using `systemu` instead. 

Why exactly is an array preferred to a string?

**Comment by segiddins** [comment]
It means we don't need to worry about shell escaping

**Comment by cbrauchli** [comment]
That's true, but is shell escaping a very error-prone process? It looks like there is already some decent shell escaping code written.

**Comment by segiddins** [comment]
I'd prefer not to chance it, and use a proper var arg version of spawn. Additionally, seeing as the issue you linked to has been closed as un reproducible, and I have been unable to replicate it myself, I'd like to see the hang in action before making changes. 

-Samuel E. Giddins

On Apr 17, 2015, at 6:36 PM, Chris Brauchli <notifications@github.com> wrote:

That's true, but is shell escaping a very error-prone process? It looks like there is already some decent shell escaping code written.

**Pull request closed without merging**
