### PR TITLE
[Frameworks] Add project/dylib/compatibility versions.

### PR DESCRIPTION
**Pull request by mrackwitz**
This was originally from #2976.
Back then, I lost this change through a rebase and force push, just before we merged the long running swift branch into master. I somehow forgot, that I wanted to fix that. Here it is again finally.

### CODE REVIEW

**Comment by segiddins** [comment]
@mrackwitz build failed on CI.

**Comment by alloy** [comment]
Hahaha, didn’t even notice that this was still not put back in :smile:

**Comment by mrackwitz** [comment]
@segiddins: Yes, it's still the integration spec.

**Comment by segiddins** [comment]
:+1:

**Pull request merged**
