### PR TITLE
Show warning when Pod source uses unencrypted HTTP

### PR DESCRIPTION
**Pull request by KrauseFx**
This PR addresses the first half of #7238, related to #7250 

Via https://github.com/CocoaPods/CocoaPods/pull/7249

### CODE REVIEW

**Comment by KrauseFx** [comment]
Let's see what the good Travis has to say

**Comment by KrauseFx** [comment]
It's 💚

**Comment by Coeur** [comment]
@KrauseFx is it possible to configure your Podfile or a commandline parameter (`pod update -something`) to automatically replace http sources with equivalent https sources?

**Comment by KrauseFx** [comment]
@Coeur I don't think that would work well, as there is no guarantee that HTTPs is supported by the host. I think reaching out to the Pod's author is the way to go here, they should fix their issue ASAP.

**Pull request merged**
