### PR TITLE
[Installer] Fix source locking/unlocking

### LINKED ISSUE #4059: Question
Hi. When i try to add XNGAPIClient in my xcode project Pod file it shows error. ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+%2FUsers%2Farmenuhi%2FDownloads%2Funtitled+folder%2Fgnix-ios%2FPods%2FHeaders%2FPrivate%2FXNGAPIClient%2FNSDictionary%2BTypecheck.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data! 

 What it means, Can any one help?

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4059.
\c @mglidden

### CODE REVIEW

**Comment by segiddins** [comment]
@keith I believe you might also be interested in this?

**Comment by keith** [comment]
Awesome! Thanks!

**Comment by segiddins** [comment]
Can either of you verify this fix works?

**Comment by segiddins** [comment]
I've verified manually that this fixes things on clean installs. @CocoaPods/core please review.

**Comment by segiddins** [comment]
Merging later today unless there are any objections.

**Comment by neonichu** [comment]
:+1:

**Pull request merged**
