### PR TITLE
typo in embed frameworks script

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* typo  
  [Coeur](https://github.com/Coeur)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Thanks! This will require integration specs update unfortunately

**Comment by Coeur** [comment]
@dnkoutso done at https://github.com/CocoaPods/cocoapods-integration-specs/pull/173

**Comment by dnkoutso** [comment]
can you please rebase/squash and also add a more descriptive commit message? "Fix typo in embed frameworks script phase" for example.

**Pull request merged**
