### PR TITLE
[ISSUE_TEMPLATE] Initial proposal

### PR DESCRIPTION
**Pull request by mrackwitz**
As seen in the [recent blog post](https://github.com/blog/2111-issue-and-pull-request-templates) on the GitHub blog, it's possible to create templates for issues and pull requests from now on. This PR should get the ball rolling for us and give a starting point for discussion.

Keep in mind that the template should be optimized in terms of readability as non-interpreted markdown as well.

### CODE REVIEW

**Comment by segiddins** [comment]
Please move the github-specific files to a `.github` directory

**Comment by segiddins** [comment]
I feel like we should do a better job of prompting people to upload a whole project instead of just a Podfile, since that's almost always the first thing we ask for

**Comment by mrackwitz** [comment]
>Please move the github-specific files to a .github directory

I'm fine with that for the templates. But I would leave `CONTRIBUTING.md` located in the root of the repo, where it is currently.

**Comment by segiddins** [comment]
Sure.

**Comment by orta** [comment]
:+1:

**Comment by neonichu** [comment]
:+1: for asking for a project, also because way too many issues include "create a new project" as part of steps to repro it.

**Comment by orta** [comment]
Let's get this in as-is, it's much better than the nothing we have currently, and we can figure out wording around including a project.

**Pull request merged**
