### PR TITLE
[Resolver] Move side-effect of storing head pods from #specs_by_target

### PR DESCRIPTION
**Pull request by mrackwitz**
… to #resolve.
Methods, which work like getters, shouldn't have side-effects.

### CODE REVIEW

**Comment by segiddins** [comment]
Sure, this is fine, though I fail to see the motivation for changing this, since it's entirely non-functional.

**Comment by mrackwitz** [comment]
I stumbled on that when working on something else and saw at as an origin of potential unwanted consequences and that I just spent a moment on double-checking that's not called twice was already too much.
… and less code is better code. :grimacing:

**Comment by segiddins** [comment]
👍🏻🚢

In the future, feel free to just push refactors like this, as long as the specs pass

-Samuel E. Giddins

On May 10, 2015, at 12:50 PM, Marius Rackwitz <notifications@github.com> wrote:

I stumbled on that when working on something else and saw at as an origin of potential unwanted consequences and that I just spent a moment on double-checking that's not called twice was already too much.
… and less code is better code.

**Comment by mrackwitz** [comment]
I will insist on going over CI and code review.

**Pull request merged**
