### PR TITLE
Fix typo when integrating Swift pods as static libraries

### LINKED ISSUE #7495: Wrong command suggestion for `use_modular_headers!`
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run CocoaPods with `master` on a project that imports RealmSwift.

## What did you expect to happen?

It would print the right command to add to the Podfile (`use_modular_headers!`)

## What happened instead?

```
The swift pod `RealmSwift` depends upon `Realm`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from swift when building as static libraries), you may set `use_modular_header!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

The suggestion is `use_modular_header!` (in singular form) which is not the valid syntax. Also a small nitpick: `swift` should be capitalized.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.3 (9Q127n)
         Git : git version 2.16.1
Ruby lib dir : /Users/marcelofabri/.rvm/rubies/ruby-2.4.0/lib
Repositories :  master - https://github.com/CocoaPods/Specs.git @ b397495429be9b9e20da413bc814dba2a8c59f9f
```

### Installation Source

```
Executable Path: /Users/marcelofabri/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!(false)

target 'XX' do
  
  pod 'Pulley'
  pod 'RealmSwift'

  target 'XXTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
```

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #7495 

I haven't run the tests locally, but I hope they'll pass 🙌

### CODE REVIEW

**Comment by dnkoutso** [comment]
I think it should be good. Maybe integration specs need updating but I will let you know how to update them if thats the case.

**Comment by dnkoutso** [comment]
@marcelofabri :

```
raises when a swift target depends upon a target that does not define a module [FAILED]
```

**Comment by marcelofabri** [comment]
Updated, I missed one `swift` on the test.

**Comment by dnkoutso** [comment]
thanks!

**Comment by marcelofabri** [comment]
🎉

**Pull request merged**
