### PR TITLE
Fix validation failure from new xcodeproj settings

### PR DESCRIPTION
**Pull request by amorde**
Fixes https://github.com/CocoaPods/CocoaPods/issues/12664

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]

**Review by dnkoutso — APPROVED** [review]

**Comment by paulb777** [comment]
Confirmed the fix fixes my repro case and running full Firebase CI at https://github.com/firebase/firebase-ios-sdk/pull/13989

**Comment by paulb777** [comment]
Hmm, while my Gemfile patch works locally, there's a ruby error in GitHub Actions, so I think I'll need to wait for release to do a full test.

**Comment by amorde** [comment]
> `require': cannot load such file -- cocoapods (LoadError)

huh, weird.. does that repro if you retry the job?

**Comment by paulb777** [comment]
> > `require': cannot load such file -- cocoapods (LoadError)
> 
> huh, weird.. does that repro if you retry the job?

It seems to be happening on the pod lib lint runs for all the Firebase products https://github.com/firebase/firebase-ios-sdk/pull/13989

**Comment by amorde** [comment]
Ok, well I'll go ahead and merge as it seems unrelated.

**Pull request merged**
