### PR TITLE
For fix slow dependency issus.

### PR DESCRIPTION
**Pull request by yanzhiwei147**
for issue #5180

### CODE REVIEW

**Comment by segiddins** [comment]
Can you give us some performance numbers on this change?
Also, CI failed, could you take a look at that?

**Comment by yanzhiwei147** [comment]
@segiddins I fix this issue base on 0.39.0,it's a question?

**Comment by segiddins** [comment]
I'm sorry, I don't understand your question

**Comment by jafara** [comment]
@yanzhiwei147 are you planning on finishing this PR? I am interested in the gains we will get for speed performance.

**Comment by yanzhiwei147** [comment]
@segiddins I change source code base on tag [0.39.0](https://github.com/CocoaPods/CocoaPods/tree/0.39.0), but make this PR must commit to the master branch? I don't know you can understand my question?

**Comment by yanzhiwei147** [comment]
@jafara So what can i help you?

**Comment by segiddins** [comment]
Yeah, you need to make the PR against master

**Pull request closed without merging**
