### PR TITLE
Include test schemes within library schemes

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/CocoaPods/CocoaPods/issues/6765

### CODE REVIEW

**Comment by DanToml** [comment]
Would be nice to see a test for this, but it LGTM

**Comment by dnkoutso** [comment]
@DanToml +1 on adding a test. I always want to :) This was a bit tougher at a first glance but i will try again.

**Comment by dnkoutso** [comment]
@DanToml spent another hour or so on this to add a spec. I am having a hard time setting up everything in order to write it. You know me I dislike merging stuff without tests but I think this should be good.

Please push back if I should spend more time on this and follow up with a spec. Will merge for now.

**Comment by DanToml** [comment]
@dnkoutso seems fine :+1:

**Pull request merged**
