### PR TITLE
Update cocoapods-trunk gem minimum version requirement.

### PR DESCRIPTION
**Pull request by jrullman**
Fixes CocoaPods/CocoaPods#11040

### CODE REVIEW

**Comment by dnkoutso** [comment]
This wont fix the issue I thnk we need this https://github.com/CocoaPods/trunk.cocoapods.org/pull/317 to land.

**Comment by jrullman** [comment]
Are you saying the linting is happening on the server side using code from cocoapods-core?

**Comment by dnkoutso** [comment]
The linting happens locally however the serialization of the podspec happens in the trunk service. 

If you are seeing a lint error locally you might need to do `bundle update cocoapods-trunk`. The version requirement you changed wont have an effect much the requirement accepts the latest version of cocoapods-trunk which 1.6.0.

However, I hope readme or changelog are properly serialized by trunk in the version its on when the pod is published.

**Comment by jrullman** [comment]
The publishing works fine - we have been doing it for several releases now using --allow-warnings.

How do we force `gem install cocoapods` to update cocoapods-trunk to 1.6.0 and use the latest version?

**Comment by dnkoutso** [comment]
You cannot but I think we accept the PR you made. This can be for cocoapods 1.12.

**Comment by dnkoutso** [comment]
btw I think `gem install cocoapods` _should_ choose the 1.6.0 version. Its possible its just an outdated machine that had run `gem install cocoapods` when 1.4.0 was the only released version.

**Pull request merged**
