### PR TITLE
[IntegrationSpecs] Update for building with Ruby 2.2 and Xcode 7

### PR DESCRIPTION
**Pull request by segiddins**
@CocoaPods/core are y'all good with this?

### CODE REVIEW

**Comment by neonichu** [comment]
Why Ruby 2.2? IMO we should stay on the same version as system ruby (currently 2.0.0p645).

**Comment by supermarin** [comment]
^^ this

**Comment by segiddins** [comment]
The only difference is in the quoting of the generated YAML files, and it means we can regenerate the specs faster.

**Comment by k0nserv** [comment]
> The only difference is in the quoting of the generated YAML files, and it means we can regenerate the specs faster.

Wouldn't this leave us open to accidentally using 2.2 features and it not being caught by CI which would then mean that cocoapods would not work on system ruby?

**Comment by segiddins** [comment]
Nope, CI would still test on 2.0.0

**Comment by neonichu** [comment]
OK, since this causes no issues with testing against 2.0, I'm all :+1:

**Comment by k0nserv** [comment]
Same :+1:

**Pull request closed without merging**
