### PR TITLE
Fixing frameworks with Today Widgets

### LINKED ISSUE #790: "A signed resource has been added, modified, or deleted" error for CocoaPods with .xib files
Screen Shot 2013-02-10 at 10 15 35 AM

I have seen the above error message a number of times while using CocoaPods on two different projects.

If I run

```
 codesign --verify --verbose /path/to/MyApp.app
```

on my app, it can tell me why the verification failed.  The response that I receive is:

```
 resource modified: /path/to/MyApp.app/GTMOAuth2ViewTouch.nib
```

which, in this case, is a nib file from the gtm-oauth2 CocoaPods package.  I had a similar problem with another CocoaPods project, which also included a nib file.

It also does not occur the first time I compile a project, or if I clean the project and then build, which makes it seem as if the problem is something like: during the "Copy Pods Resource" phase, ibtool will touch the nib file _after_ the codesign process or perhaps that codesign is, for some reason, signing the app with the _old_ .nib rather than the new one.

Anyway, as a fix, I have added the script "rm -rf ${BUILT_PRODUCTS_DIR}" to the Pre-actions of the Build stage of my Scheme, which seems to fix the problem, but perhaps there is a way of handling the copy script which can make this unnecessary.

### LINKED ISSUE #1546: Pods copy resource script overrides default xcasset bahaviour
I have a project with different "themes" that are used for different xcode targets. For the themes I have two xcasset catalogs, one with red graphics and one with green graphics. Inside the bundles the files are named the same (so that I can simply use background.png as image name and get the correct color). Which xcasset that get copied is determined by the target membership (and ultimately by the build step "copy bundle resources").
Since cocoa pods version 0.27 I've noticed that there is a new entry in the copy pods resource script. That will cause my red graphics copied by the standard xcode build step to be replaced with the green graphics copied by the cocoa pods copy resources build step.

### PR DESCRIPTION
**Pull request by chrisfsampaio**
Adding Modules to the excluded list folders in order to make Today Widgets sign in properly, might fix #790

### CODE REVIEW

**Comment by segiddins** [comment]
@chrisfsampaio could you please explain why this is the correct fix to the problem?

**Comment by chrisfsampaio** [comment]
I wish I could tell it for sure, I'm very new to how CocoaPods works internally. Nevertheless here is the output of my humble investigation on the problem:

The *modules* folder is excluded by the build step that copies the .appex package (Today Widget executable) to the Plugins folder, here is the report generated by Xcode Report Navigator excluding the Modules folder:

```shell
PBXCp /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyAppTodayExtension.appex /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex
    cd /Users/christian/code/MyApp-ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/christian/.rvm/gems/ruby-2.1.2/bin:/Users/christian/.rvm/gems/ruby-2.1.2@global/bin:/Users/christian/.rvm/rubies/ruby-2.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/christian/.rvm/bin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -resolve-src-symlinks /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyAppTodayExtension.appex /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns
```
Now here is the part I'm not very sure of:
AFAIK, this build step is automatically created by Xcode when a Today Widget is created. The problem is that the code signing made on the CocoaPods script *does* include the modules folder, therefore the App installations fails.

Here is the output of a manual code signing verification I ran on the build folder:

```shell
$codesign --verify --verbose MyApp.app/PlugIns/MyAppTodayExtension.appex

MyApp.app/PlugIns/MyAppTodayExtension.appex: a sealed resource is missing or invalid
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/CocoaLumberjack.framework/Modules/module.modulemap
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/YapDatabase.framework/Modules/module.modulemap
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/UIImage_BlurredFrame.framework/Modules/module.modulemap
```

Again, I might be wrong about it, but my problem has been solved after modifying the CocoaPods script :smiley: 

I've created an empty project to reproduce the problem using the following steps:
1) Create an empty simple project and add the sample Today Widget provided by Xcode template.
2) Touch the Podfile:
```ruby
use_frameworks!
pod 'Alamofire'
link_with 'TestBugTodayWidget', 'TodayWidget'
```
3) Run ```pod install```
4) Try to run the main target __on the device__
The following error appears:
screen shot 2015-04-13 at 6 50 54 pm

[Here](http://cl.ly/1p2K1u3s471n/download/TestBugTodayWidget.zip) is the sample project.

Sorry for the wall of text :see_no_evil:

**Comment by mgbaozi** [comment]
This commit resolve my problem, thanks.

**Comment by jvanderwee** [comment]
This resolved the problem for me too, thanks.

**Comment by l2succes** [comment]
Fixed my issue as well, thx. Let's get this PR merged in plz ;)

**Comment by segiddins** [comment]
@mrackwitz @neonichu please take a look at this?

**Comment by neonichu** [comment]
This looks legit - open question to me is if it is limited to extensions. Currently, the change would impact everything.

**Comment by chrisfsampaio** [comment]
@neonichu You are right. But the following line reassigns the package with the current state (without the Modules folder). The final .app package seems to be independent of the Modules folder to run, since I've been using and importing CocoaPods dependencies in the main target and the extension without  problems. 
In my understanding, the Modules map [is only necessary to compile the code by linking "external" code properly](http://clang.llvm.org/docs/Modules.html#semantic-import), which is before the final-package-creation-code-signing step.

**Comment by neonichu** [comment]
@chrisfsampaio you are right in that is shouldn't be needed at runtime, would be just nice to verify if Xcode skips the "Modules" directory for other targets as well or not.

**Comment by chrisfsampaio** [comment]
The step that skips the Modules folder on the extension is the one the copies its contents from the root build folder to the Plugins folder, since it's copying a signed in package by excluding some part, it fails. There is no such step on the main target. The main target is used *as is* after the link dependencies step, which has no mention of skipped files:
```shell
Ld /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Products/Debug-iphoneos/MyApp.app/MyApp normal arm64
    cd /Users/christian/code/Movile/MyApp
    export IPHONEOS_DEPLOYMENT_TARGET=8.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/christian/.rvm/gems/ruby-2.1.2/bin:/Users/christian/.rvm/gems/ruby-2.1.2@global/bin:/Users/christian/.rvm/rubies/ruby-2.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/christian/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk -L/Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Products/Debug-iphoneos -F/Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Products/Debug-iphoneos -F/Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Products/Debug-iphoneos/Pods -filelist /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/MyApp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -ObjC -framework Alamofire -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/MyApp.swiftmodule -miphoneos-version-min=8.3 -weak_framework Pods -Xlinker -dependency_info -Xlinker /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/MyApp_dependency_info.dat -o /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-cqbpntyminznvscffjobfakjfmcn/Build/Products/Debug-iphoneos/MyApp.app/MyApp
```

**Comment by kylef** [comment]
Merged in via 6a456ad.

Thanks for the pull request.

**Comment by chrisfsampaio** [comment]
👍👊

**Pull request closed without merging**
