### PR TITLE
Added `source` and valuable flags to Podfile template

### PR DESCRIPTION
**Pull request by JamieREvans**
All Podfiles should specify a `source` and with the growing number of Swift applications, having the `use_frameworks!` flag available is also very helpful.

Also, including the `inhibit_all_warnings!` will usually save a google search, as well. Most people haven't memorized all of the common cocoapod flags.

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks for the PR, but I'd be against encouraging the use of `inhibit_all_warnings!` more — having to Google that will hopefully also give folks more time to think if they really want it :)

**Comment by orta** [comment]
> source 'https://github.com/CocoaPods/Specs.git' 

is also optional, you only need it if you use a private specs repo

**Comment by orta** [comment]
but updating to 9.0 as the default, and making `use_frameworks!` default too feels like a good call nowadays.

**Comment by JamieREvans** [comment]
@neonichu Why encourage against `inhibit_all_warnings!`? Is it to encourage developers to fix their beloved pods and rid them of warnings? I can remove the flag, though.

@orta I guess I've used private specs enough to think that warning was default for all Podfiles. As for the platform, I'd like to update my PR to reflect an 8.0 platform (as that will be the most common, no?) and maintain the `use_frameworks!` comment, as well.

Would those changes be helpful?

**Comment by JamieREvans** [comment]
Also, I've updated the PR to reflect your feedback. Let me know if you'd like to make any changes to it and why; I'd like to learn.

**Comment by orta** [comment]
8 is cool, I'm :+1:  for this change

**Comment by JamieREvans** [comment]
I've merged in the latest master and the build is passing - the sooner we resolve this PR, the more likely I won't have to do another merge! :smile:

**Comment by segiddins** [comment]
:+1: @orta feel free to merge

**Comment by orta** [comment]
:dancers: 
Thanks @JamieREvans !

**Pull request merged**
