### PR TITLE
Cache read_file_system invocations globally

### PR DESCRIPTION
**Pull request by jverkoey**
Context: My repository includes a couple git repositories that include a few thousand files/folders.
I was finding that `pod install` times were creeping to upwards of 1 minute. After this change `pod install` takes ~20 seconds, or roughly a 2/3 reduction.

## How I profiled the problem

I profiled a local checkout of the 0.39.0 pod command with ruby-prof:

    ruby-prof -p call_stack pod -- install --no-repo-update > rubyprof.html
    open rubyprof.html

The results pointed to `Pod::Installer::FileReferencesInstaller#refresh_file_accessors` being the most expensive call.

I added logging statements to `refresh_file_accessors` and saw that the method was being called multiple times on the same root path. Each call took a few seconds.

Based on the above information I implemented this change.

## The change

The change introduces a static Hash in the `PathList` object. The Hash caches results from `read_file_system` and allows `read_file_system` to reuse previously-calculated results for identical paths.

### CODE REVIEW

**Comment by jverkoey** [comment]
Some questions:

- Are we still patching 0.39.0?
- What other ways could we cache this information?
- Why is pod scanning the entire directory structure?

**Comment by jverkoey** [comment]
rubocop's last recommendation is to `Replace class var @@file_system_cache with a class instance var.` Does this simply translate to "don't use static variables"?

An alternative way to structure this change could be to pass a cache object to the PathList object. Will look into that approach if there's desire to move forward with this :)

**Comment by segiddins** [comment]
@jverkoey unfortunately, this won't work, as `read_file_system` is _explicitly_ called to clear the cache, and not allowing that to happen can cause stale files to be picked up by some of the globs. I can't know for sure without seeing your Podfile, but my guess is that you're running into this issue because you have a pod that is being used for multiple platforms? (or different sets of subspecs for your targets).

**Comment by segiddins** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
