### PR TITLE
Ensure source urls are set when spec has subspecs with dependencies

### PR DESCRIPTION
**Pull request by dnkoutso**
Regressed from https://github.com/CocoaPods/CocoaPods/pull/6576/files#diff-c40545c38369a7fb9be6a8849d065059R32

### CODE REVIEW

**Comment by dnkoutso** [comment]
🤞 for ✅  build

**Comment by orta** [comment]
🍏

**Comment by dnkoutso** [comment]
@orta may I merge?

**Comment by dnkoutso** [comment]
Going for it. Low risk change with a test and confirmed it with a pod locally.

**Comment by orta** [comment]
👍 :D

**Pull request merged**
