### PR TITLE
Set ruby-macho version to be greater than or equal to 1, less than 3

### PR DESCRIPTION
**Pull request by PeqNP**
This PR refers to this discussion https://github.com/CocoaPods/CocoaPods/issues/10390

In short, some xcframeworks are failing to be parsed by the `ruby-macho` dependency. Version 2.x (5?) fixes this issue. The result is that dependencies will not be considered a valid dynamic library and have a corresponding `install_framework` command added to the project's respective frameworks bash script.

### CODE REVIEW

**Comment by PeqNP** [comment]
I'm pretty sure I know why 2.3 is failing. I believe `ruby-macho` needs ruby version 2.4 or higher to build. I believe I saw that error when I was attempting to install this dependency with 2.3.8 on macOS. I believe 2.3 isn't supported either.

**Comment by PeqNP** [comment]
Yes. Confirmed. https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

**Comment by dnkoutso** [comment]
I believe there is a pR up to bump cocoapods to use Ruby 2.6?

**Comment by dnkoutso** [comment]
See https://github.com/CocoaPods/Core/pull/671

**Comment by igor-makarov** [comment]
@dnkoutso there's no [Ruby deprecation PR yet](https://github.com/CocoaPods/Core/pull/669#issuecomment-766372494) for CocoaPods, but it's coming in the near future.

**Comment by dnkoutso** [comment]
@PeqNP this should now be unblocked if you rebase. We bumped min version to >= Ruby 2.6.

**Comment by PeqNP** [comment]
Should be good now 🌈

**Comment by igor-makarov** [comment]
Looks like the rebase contains many existing commits, mind dropping them?

**Comment by PeqNP** [comment]
Hm. I have no idea what I'm doing. I haven't done a rebase in years to another remote. At this point I may as well create another PR and try again. I'm not sure how to back out of the current state. I'm not sure when I'm going to have time to figure this out either.

**Comment by dnkoutso** [comment]
For https://github.com/CocoaPods/CocoaPods/issues/10390

**Comment by dnkoutso** [comment]
@PeqNP i will take over this.

**Comment by dnkoutso** [comment]
Closing in favor of https://github.com/CocoaPods/CocoaPods/pull/10396

**Pull request closed without merging**
