### PR TITLE
[Gemspec] Bump ruby-macho to '~> 1.4'

### LINKED ISSUE #8529: Embed frameworks build phases missing after running `pod install`
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Created a brand new sample iOS single view project
2. Created a new Podfile, with the following contents:

```ruby
platform :ios, '12.0'

target 'Simple Sample' do
  pod 'Reveal-SDK', :configurations => ['Debug']
end
```

3. Run `pod install`
4. Opened Simple Sample.xcworkspace
5. Run the app in Xcode

## What did you expect to happen?

The app to run without issue.

## What happened instead?

The app crashed at launch due to the missing vendor framework that should have been provided by CocoaPods:

```
dyld: Library not loaded: @rpath/RevealServer.framework/RevealServer
  Referenced from: /Users/tonyarnold/Library/Developer/CoreSimulator/Devices/70E3F476-9F99-4B34-B9C6-094A51FAEADF/data/Containers/Bundle/Application/F2C25678-8E2E-451B-9A92-9A62DF3AAD0E/Simple Sample.app/Simple Sample
  Reason: image not found
```

It appears that no [CP] Build Phases save for the manifest check have been created.

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /Users/tonyarnold/.rbenv/versions/2.5.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 95325f661b91e197f987932030ea63362fddcaee
```

### Installation Source

```
Executable Path: /Users/tonyarnold/.rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '12.0'

target 'Simple Sample' do
  pod 'Reveal-SDK', :configurations => ['Debug']
end
```

## Project that demonstrates the issue

[Simple Sample.zip](https://github.com/CocoaPods/CocoaPods/files/2884018/Simple.Sample.zip)

### PR DESCRIPTION
**Pull request by woodruffw**
cc @dnkoutso

Fixes #8529.

### CODE REVIEW

**Comment by amorde** [comment]
I think `Gemfile.lock` needs to be updated as well

**Comment by woodruffw** [comment]
Yeah, just squashed a `Gemfile.lock` update into the commit (sorry, old habits).

**Comment by amorde** [comment]
No worries, I think I commented _right_ after that haha

**Comment by amorde** [comment]
Thanks for the quick fix @woodruffw ❤️

**Comment by amorde** [comment]
@dnkoutso this would be nice to port to the next 1.6 stable release

**Comment by woodruffw** [comment]
No problem! Thanks for the quick report and turnaround!

**Comment by dnkoutso** [comment]
Yes I am going to cherry-pick this to 1-6-stable.

**Comment by tonyarnold** [comment]
Is there a planned date for a stable release including this fix? I'm directing my users to downgrade to a version of the vendored framework that doesn't contain an arm64e slice, but it'd be nice to say "Just update CP" 👍 

Thanks for the quick turnaround on this fix, too!

**Comment by dnkoutso** [comment]
I am going to release 1.6.1 this week most likely which will include this.

**Comment by tonyarnold** [comment]
Excellent, thanks!

**Pull request merged**
