### PR TITLE
[Installer] Make the transitive static check accept a single transiti…

### PR DESCRIPTION
**Pull request by segiddins**
…ve pod target

\c @neonichu @mergesort

### CODE REVIEW

**Comment by neonichu** [comment]
Does this actually work in practice? The dependent Pod will not be linked against its transitive dependency and will not compile, right?

**Comment by segiddins** [comment]
I'm kinda thinking we should just always apply the Parse hack to statically link the static binaries into a dynamic binary (we actually do that at Realm under the hood)

**Comment by segiddins** [comment]
(I'd be happy to roll that up into https://github.com/CocoaPods/CocoaPods/pull/3832)

**Comment by neonichu** [comment]
Well, the issue with that is that it doesn't work for all static libs and I haven't found out why or how to detect that it'll not work.

**Comment by segiddins** [comment]
Can you give an example of when it doesn't work?

**Comment by neonichu** [comment]
See #3106

**Comment by perotinus** [comment]
I can give one reason why it might not work for every static library: if that library was compiled ```-fvisibility=hidden```, then when it's linked into a dynamic library, the symbols aren't reexported, no matter what you do. 

I haven't found an easy way to detect it. You seem to need to compile the static library into a dynamic one and run ```nm -g``` to see which symbols are being exported. The fix is for Pod owners to recompile their ```vendored``` pods with ```-fvisibility=default``` or with proper visibility ```__attribute__```s.

**Comment by neonichu** [comment]
@perotinus thanks for the hint, I'll see if that is the cause. Unfortunately, having to compile something first to see if it works doesn't sound like a good option for CP to decide the integration strategy.

**Pull request closed without merging**
