### PR TITLE
Add deployment target option for ibtool command in copy resources script

### PR DESCRIPTION
**Pull request by manuyavuz**
This solves #4388

However, I'm not sure if this also works for os x targets because I'm adding deployment target using `IPHONEOS_DEPLOYMENT_TARGET` environment variable.

PS: Travis will fail for integration tests. I will send a PR updating integration specs repo also.

### CODE REVIEW

**Comment by segiddins** [comment]
Hm so I think we'll need to calculate the deployment target based upon the platform were building for

**Comment by segiddins** [comment]
Maybe `${${SDKROOT}_DEPLOYMENT_TARGET}`?

**Comment by manuyavuz** [comment]
It won't work because SDKROOT is the path of the sdk.

I see the following env variable:

```
DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
```
I think it could work via `${${DEPLOYMENT_TARGET_SETTING_NAME}}`

Thoughts?

**Comment by segiddins** [comment]
ah yeah, that should do it

**Comment by manuyavuz** [comment]
Even though I don't fully get what `!` character provides, true way is the following:

```
${!DEPLOYMENT_TARGET_SETTING_NAME}
```

I will update accordingly.

**Comment by manuyavuz** [comment]
Made the change. I think we need to update cocoapods-deintegrate plugin along with cocoapods-integration-specs submodule. Can send a PR for that also.

**Comment by segiddins** [comment]
Don't worry about the integration specs, I update them once I merge the CocoaPods PR. Why would deintegrate also require a change?

**Comment by manuyavuz** [comment]
I see that it also contains test project structures inside spec fixtures which contain copy resource script in the old way. 

Great for integration specs, I'll close the PR on that repo then.

**Comment by segiddins** [comment]
:+1: will merge this this afternoon with everything else, well done @manuyavuz

**Pull request merged**
