### PR TITLE
Integrate Code of Covenant 1.2.0 changes

### PR DESCRIPTION
**Pull request by neonichu**
Supersedes #3705

I have fixed the broken URL and incorporated 1.2.0 changes.

We still have to agree on a wording for when contributors are actively representing the project — I didn't really feel we reached a conclusion in the earlier discussion.

cc @alloy @samdmarshall

### CODE REVIEW

**Comment by neonichu** [comment]
How about:

> This code of conduct applies both within project spaces and in public spaces when an individual is actively representing the project or its community. Due to their strong association with the project, core contributors are always seen as actively representing it.

**Comment by samdmarshall** [comment]
That sounds good to me

**Comment by segiddins** [comment]
I'm in favor of using the contributor covenant unmodified

**Comment by alloy** [comment]
@neonichu Yeah that sounds good to me too :+1:

**Comment by orta** [comment]
alright, :ship:

**Pull request merged**
