### PR TITLE
[AggregateXCConfig] Set EMBEDDED_CONTENT_CONTAINS_SWIFT when using a …

### PR DESCRIPTION
**Pull request by segiddins**
…Swift pod

This will allow us to merge https://github.com/CocoaPods/CocoaPods/pull/4221.

- [x] CHANGELOG
- [x] Tests

\c @mrackwitz @neonichu

### CODE REVIEW

**Comment by neonichu** [comment]
This did nothing bad when Xcode 6 was involved, right? It just didn't work?

**Comment by segiddins** [comment]
@neonichu correct

**Comment by segiddins** [comment]
This should be good to go now (integration spec failures are expected)

**Comment by neonichu** [comment]
:+1:

**Comment by mrackwitz** [comment]
:+1:

**Comment by orta** [comment]
I want in on this thumb action

photo on 25-09-2015 at 16 32 2

**Pull request merged**
