### PR TITLE
Automatically lock Pod source files after installing (#1154)

### PR DESCRIPTION
**Pull request by mglidden**
🌈

Seems like this should probably be the default behavior, instead of a plugin. When this gets released, I'll deprecate the plugin and put up a note saying that it's now built in.

### CODE REVIEW

**Comment by segiddins** [comment]
I really don't want to do this -- I don't like it when tools other than `chmod` change file permissions on me, and I'd hate for CocoaPods to start making it so people have trouble deleting the files it owns.

**Comment by mglidden** [comment]
While it would warn you when trying to delete specific files, you can still delete the entire Pods folder without any trouble.

Having trained a bunch of people to use CocoaPods, I've found the lack of locking to be huge usability issue. I've seen several developers not realize they were editing a Pods file, causing them to either lose their work or introduce a bug.

**Comment by segiddins** [comment]
Well, that can be gotten around by either (1) not editing files in the pods project to begin with (2) the plugin you made (3) not checking in the Pods directory.

**Comment by mglidden** [comment]
The entire problem is due to the developer not realizing they were editing a file in the pods project. This is primarily a concern for developers new to CocoaPods or the codebase their working on.

Checking in the Pods directory creates an even tricker problem. If a developer edits & commits something, then someone updates the pod, the changes will be blown away. So the problem might go unnoticed for a while before causing a bug. This edge case is not covered by this PR.

While the plugin works, it doesn't help new users (the ones most hit by this issue) who have no idea it exists.

**Comment by neonichu** [comment]
@mglidden you can make the plugin mandatory by including it in your Podfile:

```
plugin 'cocoapods-readonly'
```

**Comment by orta** [comment]
@kylef got opinions on this? I'm relatively neutral, with a bias towards merging it in. Things like this and the 2 Xcode plugins all exist to try and make the conceptually immutable pods actually so. I think it's a reasonable expectation that libraries that aren't meant to be edited as made that way.

> I don't like it when tools other than chmod change file permissions on me

These are files "created" and maintained by CocoaPods though, so it's not as if we're going and making fundamental changes to the users lib folders.

**Comment by kylef** [comment]
@orta I'm for this, I re-opened #1154 when I discovered this solution.

**Comment by orta** [comment]
Let's :shipit: - I think this is a better user experience.

**Comment by cdzombak** [comment]
I didn't realize this was being included in cocoapods itself; thanks! I've been using and loving https://github.com/Yelp/cocoapods-readonly/ since day 1.

**Comment by kraftydevil** [comment]
This breaks my workflow after updating from 0.33.0 to 0.38.0.

Is it possible to disable this feature in 0.38.0? Preferably on a per-pod basis?

If disabling is not available in the current version, then here's why the feature is giving me trouble:

I often work on my own private library pod on the project(s) using that pod. This way I can test it out before having to 'pod update'.

If everything looks good, I have a script to copy the changes from my project to to the directory where my library pod resides on my machine.

I've found this to be much easier than writing guess-code in my library, pushing changes, calling pod update on the client project and THEN finally getting to see if my changes worked.

The feature is meant to protect me against something that I'm very much aware of. I can see how it makes sense for pods that I didn't write and have no intention of modifying.

It's just easier to them directly. Xcode does give me the option to Unlock the file but it's too much to hit 'Unlock' for every file I want to change.

**Comment by segiddins** [comment]
@kraftydevil sounds like you should be using development pods

**Comment by kraftydevil** [comment]
Thank you for the head's up on Development Pods. I will give it a try.

Looks like it's just what I need. I think I'm half using it already since I typically point my Podfile to a develop branch anyways. Next step appears to be to make a Podfile.local with a `:path` reference.

Using this: https://www.cocoanetics.com/2014/07/development-pods/

**Pull request merged**
