### PR TITLE
Embed frameworks into app and watch extensions.

### LINKED ISSUE #3546: Embed frameworks in application extensions
#3489 removed the "Embed Pods Frameworks" build phase from everything but application and test targets. We need to re-enable it for app extension and WatchKit extension targets, though.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #3546 

- [x] Specs
- [x] Changelog

### CODE REVIEW

**Comment by segiddins** [comment]
Looks like a good start!

**Comment by segiddins** [comment]
@neonichu if the framework is deduplicated, shouldn't the extension targets just link against the parent app's frameworks?

**Comment by neonichu** [comment]
@segiddins that doesn't appear to work in practice —maybe part of the sandboxing of app extensions that they don't have access?

**Comment by segiddins** [comment]
@neonichu did you try changing the load paths?

**Comment by segiddins** [comment]
:+1:

**Pull request merged**
