### PR TITLE
[Travis] Only build master and stable branches

### PR DESCRIPTION
**Pull request by segiddins**
\c @kylef

### CODE REVIEW

**Comment by kylef** [comment]
Won't this mean it won't test pull requests?

**Comment by segiddins** [comment]
As you can see from this PR, it will still test pull requests into one of the tested branches

**Comment by kylef** [comment]
What's the justification / reason for this change?

**Comment by segiddins** [comment]
It means we won't build branches that are just PR-ed into master/stable twice.

**Comment by segiddins** [comment]
Unless you seriously object, I'd like to merge this.

**Pull request merged**
