### PR TITLE
Check CDN repo URL procedure changed with common one

### PR DESCRIPTION
**Pull request by igorudovika**
Very small improvement that will simplify resolve https://github.com/CocoaPods/CocoaPods/issues/9151 issue

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Check CDN repo URL procedure changed with common one  
  [igorudovika](https://github.com/igorudovika)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
cc @igor-makarov

**Comment by igor-makarov** [comment]
Seems good, didn't know about that one!

**Comment by dnkoutso** [comment]
@igor-makarov any strong opinions on shipping this with 1.8 or 1.9?

**Comment by dnkoutso** [comment]
I guess its related to #9151 also and when we want to ship that.

**Comment by igor-makarov** [comment]
1.9 seems more on the safe side since it's part of some bigger work.

**Comment by dnkoutso** [comment]
Sounds good.

**Comment by dnkoutso** [comment]
This is good to merge right @igor-makarov? i.e it does not depend on something else landing?

**Comment by igor-makarov** [comment]
Doesn't depend on other PRs as far as I see.

**Comment by dnkoutso** [comment]
We are using latest master and this change actually returns a legitimate `git` repo as if it were CDN.

**Comment by dnkoutso** [comment]
This change now makes CocoaPods follows redirects which can cause a false positive in which a 200 result is returned and making CocoaPods think that the URL that is meant to be a `git` repo is CDN.

@igorudovika @igor-makarov can you weigh in on how this can be fixed? We hit this case internally.

**Comment by igor-makarov** [comment]
Can you be more specific? What gets redirected where?

**Comment by dnkoutso** [comment]
We use Stash internally and the URL for our source repo is `https://.../something/something.git`

In the code we do `https://.../something/something.git/all_pods.txt` which then redirects to another page due to this change here and we get a false positive which then fails in other ways later in the process.

**Comment by igor-makarov** [comment]
I've got no quick fix so I guess revert and let's try to figure out a grand unified HTTP client refactor later 🙃

**Comment by igorudovika** [comment]
I can work with fix for this issue.
But problem is still not clear for me. Seems `https://.../something/something.git/all_pods.txt` matches for old regex too. So mine revert of mine fix will not help

**Comment by igor-makarov** [comment]
The problem is, old logic was using an incorrect test but it didn't follow redirect so no false positive.

New logic follows redirects and therefore has a false positive.

But fundamentally the test for CDN is not correct.

**Comment by igor-makarov** [comment]
Perhaps check for content type header?

**Comment by dnkoutso** [comment]
I am going to revert temporarily and then we can discuss a proper fix.

**Comment by igorudovika** [comment]
Thanks @igor-makarov  I got you, so problem is in `validate_url` it tries to get `actual_url` by taking into account redirects.

**Comment by dnkoutso** [comment]
yeap. And I think just checking for the 200 status code is still not sufficient.

**Comment by igor-makarov** [comment]
Maybe it should GET the CP meta YML and actually parse it?

**Comment by igorudovika** [comment]
Do you mean CocoaPods-version.yml file?
if yes, what tokens I need to check in order to validate content? Existing of:
`min:`, `last:` and `prefix_lengths:` tokens?

**Comment by igor-makarov** [comment]
Yeah, that seems decently robust.

**Comment by igorudovika** [comment]
ok, then, let me prepare new fix.

**Comment by dnkoutso** [comment]
Just try to parse the whole file as YAML document might be sufficient.

**Comment by igor-makarov** [comment]
Yeah, the parser will throw if it isn't a valid meta file.

**Comment by igorudovika** [comment]
ok, I will do

**Comment by igorudovika** [comment]
Added new PR https://github.com/CocoaPods/CocoaPods/pull/9212
Seems for now this change does not contain any logic that I am interesting but perhaps you will find it useful for project. After Typhoeus lib introducing in Core repo I will try to change this logic again with new PR

**Pull request merged**
