### PR TITLE
Added possibility to skip modulemap generation

### PR DESCRIPTION
**Pull request by till0xff**
For https://github.com/CocoaPods/CocoaPods/issues/10235

Core PR: https://github.com/CocoaPods/Core/pull/664

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Added possibility to skip modulemap generation  
  [till0xff](https://github.com/till0xff)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
@till0xff this seems its missing some changes needed in Cocoapods/Core project within `dsl.rb`.

```ruby
      # @!method module_map=(module_map)
      #
      #   The module map file that should be used when this pod is integrated as
      #   a framework.
      #
      #   ---
      #
      #   By default, CocoaPods creates a module map file based upon the public
      #   headers in a specification.
      #
      #   @example
      #
      #     spec.module_map = 'source/module.modulemap'
      #
      #   @param  [String] module_map
      #           the path to the module map file that should be used.
      #
      attribute :module_map,
                :root_only     => true
```
We should add `Bool` in the `@param` section and also another example.

See example CocoaPods/Core PR here https://github.com/CocoaPods/Core/pull/412/files that did something similar for PCH generation.

**Comment by dnkoutso** [comment]
@till0xff can you add some tests for this change?

**Comment by dnkoutso** [comment]
@till0xff we merged the Core PR, can you change the `Gemfile.lock` to bump the Core gem SHA and also add tests here?

Thanks!

**Comment by till0xff** [comment]
@dnkoutso can you merge this PR?

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by cooler333** [comment]
@segiddins can you merge it?

**Review by segiddins — APPROVED** [review]

**Comment by swiftyfinch** [comment]
@segiddins @dnkoutso Hi 👋🏻 Are there any blockers here?

**Comment by dnkoutso** [comment]
@till0xff can you rebase to latest master and I will merge?

**Comment by dnkoutso** [comment]
This looks like it has a merge commit.

Can you `git rebase master` on your branch and `git push -f` so it only includes your commit?

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Looks like there is still a merge commit https://github.com/CocoaPods/CocoaPods/pull/10207/commits

**Comment by till0xff** [comment]
@dnkoutso done

**Comment by dnkoutso** [comment]
merged!

**Pull request merged**
