### PR TITLE
Fix duplicate framework/resource output paths caused by the same output file name

### LINKED ISSUE #7259: The output file entries of the Embed Pods Frameworks phase should be deduplicated.
# Report

## What did you do?

Given the following dependency specification:
```
    pod 'Onfido'            , '~> 5.0', :configurations => [ 'Debug' ]
    pod 'Onfido-Release'    , '~> 5.0', :configurations => [ 'Release' ]
```

The CocoaPods integration creates a Embed Pods Framework phase, which has the two entries of the identical file path as its output file — in this case `${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/Onfido.framework`. While this does not cause an issue with the old build system, the Xcode 9 new build system refuses to proceed unless either of the identical entries is manually removed.

## What did you expect to happen?

It should work with the Xcode 9 new build system.

## What happened instead?

The Xcode 9 new build system refuses to build the project with the said generated build phase, unless manual change is made (which gonna be overwritten by CocoaPods the next time it is invoked).

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/anders/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7e60e550a59a83a2cd6e970052fded553aab7b1
```

### Installation Source

```
Executable Path: /Users/anders/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Example
https://github.com/andersio/TestCocoaPods

### PR DESCRIPTION
**Pull request by amorde**
Closes #7259

### CODE REVIEW

**Comment by dnkoutso** [comment]
danke!

**Comment by amorde** [comment]
I think adding the error you mentioned for duplicate resources is a good idea, so I might do that in another PR. Unless you want to do it :D

**Comment by dnkoutso** [comment]
Yes another PR definitely. Feel free to tackle it. We can still ship 1.4.0 without it.

**Comment by dnkoutso** [comment]
Just need to execute `bundle exec rubocop -a`

**Pull request merged**
