### PR TITLE
Match Core gem activesupport version requirements.

### PR DESCRIPTION
**Pull request by dnkoutso**

### CODE REVIEW

**Comment by segiddins** [comment]
If core already has an activesupport requirement, is there any reaosn for us to duplicate it in cocoapods?

**Comment by dnkoutso** [comment]
Good question, I could also remove it.

**Comment by amorde** [comment]
Seems like if we were to only pick one, it would be CocoaPods and not Core. but I guess it doesn't really matter

**Comment by amorde** [comment]
This also came up on my PR for bumping minimum Ruby version https://github.com/CocoaPods/CocoaPods/pull/9851#discussion_r439585296

**Pull request merged**
