### PR TITLE
Fixes an issue which prevented using a custom `CONFIGURATION_BUILD_DIR` when integrating CocoaPods via dynamic frameworks.

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
\c @mrackwitz @neonichu @kylef

**Comment by mrackwitz** [comment]
LGTM :+1:

**Comment by neonichu** [comment]
:+1:

**Comment by segiddins** [comment]
@kylef please test this with your test app?

**Comment by mrackwitz** [comment]
Thank you for that! Especially to @timrosenblatt for your first contribution! :tada:

**Comment by timrosenblatt** [comment]
<3 @mrackwitz

**Pull request merged**
