### PR TITLE
Remove the Hooks API representation artifacts

### LINKED ISSUE #3648: Podfile `pre_install` / `post_install` Hooks API misaligned with model
The Podfile Hooks API, which can be defined via `pre_install` / `post_install` (in contrast to the plugins API) is misaligned with the current model used in CocoaPods.

The Hooks API is supposed to be a proxy layer, so we can alter the installation / integration process and the model and just change how the Hooks API representations access those artifacts.

This seem to have worked for a while. [References in the source code](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/hooks/installer_representation.rb#L86) shows that the Hooks API remains backwards-compatibility to CocoaPods <= 0.17. This is quite impressive for what has changed since then, but is in big contradiction to our often prominently self-declared state of being unstable and that anything could break with the next minor version, but it was surely mostly nice for our users.

Now methods and classes refer to names, which were prior used in the model, but are not used anymore and doesn't fit the still 'new'-ish integration with frameworks. An overhaul to that could make it more straightforward to use that API, but will break existing Podfiles.

### Current State

```
InstallerRepresentation                                    ✅
├─ sandbox_root: Pathname                                  ✅
├─ project:      Xcodeproj::Project                        ✅
├─ pods:         PodRepresentation                         ❎ see 2.
├─ libraries:    LibraryRepresentation                     ❎ see 1.
├─ specs_by_lib: [LibraryRepresentation : [Specification]] ❎ see 1.
├─ pods_by_lib:  [TargetDefinition : [PodRepresentation]]  ❎ see 3.
├─ sandbox:      Sandbox                                   ❎ internal
├─ config:       Config                                    ❎ misplaced (arguable)
└─ installer:    Installer                                 ❎ see 4.
```

```
LibraryRepresentation                                      ❎ see 1.
├─ name:                       String                      ✅
├─ dependencies:               [Dependency]                ✅
├─ sandbox_dir:                Pathname                    ✅
├─ prefix_header_path:         Pathname                    ❎ deprecated
├─ copy_resources_script_path: Pathname                    ✅ but see 5.
├─ project:                    Xcodeproj::Project          ✅
├─ target_definition:          TargetDefinition            ✅
├─ target:                     Xcodeproj::NativeTarget     ❎ rename to native_target
├─ sandbox:                    Sandbox                     ❎ internal & misplaced
└─ library:                    AggregateTarget             ❎ see 1., internal
```

```
PodRepresentation                                          ❎ see 2.
├─ name:                       String                      ✅
├─ version:                    Version                     ✅
├─ root_spec:                  Specification               ✅
├─ specs:                      [Specification]             ✅
├─ root:                       Pathname                    ✅
└─ source_files:               [Pathname]                  ✅
```

### Issues

1. `LibraryRepresentation` is as name misleading as it represents an `AggregateTarget`. Since the support of frameworks, this mismatches the actual build artifacts, while `AggregateTargets` are merely intermediate build artifcats as implementation detail when integrating with libraries.
2. `PodRepresentation` is wobbly as it's unclear whether that represents a `PodTarget`, a `Dependency` or a `Specification`. As we all know, a given specification can be integrated multiple times in different variants (platform, subspecs). Currently there is only one `PodRepresentation` for each root spec, which holds all file accessors for it. This is wrong.
3. `InstallerRepresentation#pods_by_lib` is probably supposed to return a `{ LibraryRepresentation => [PodRepresentation] }`, like documented and analog to `#specs_by_lib`. The implementation does something else currently. Generally, a `TargetDefinition` is easier to retrieve than a `LibraryRepresentation` with a programmatic reference to the `Podfile`, but that's not exposed to the Podfile itself. But without this hash the structure of `LibraryRepresentation => [PodRepresentation]` isn't represented at all. So one idea would be to represent that as a relation from `LibraryRepresentation` to `PodRepresentation`. A hash with `LibraryRepresentations` by name on `InstallerRepresentation` would then make it easy to navigate in the proxy layer.
4. The general goal is to limit the accessible API to the public API of Core, Xcodeproj and the Ruby Standard libraries. When giving access to the `Installer` directly, it is easier to access the underlying model, which makes the whole effort of the Hooks API questionable.
5. What should be accessible from the Hooks API and what not?

### Actionable Items:

* [x] **1.** Do we need the hooks in the Podfile at all? See also CocoaPods/Core#243.
* [ ] **2.** If 1., do we want to maintain a proxy layer? Alternatively we could just expose the `Installer` together with `AggregateTarget` and `PodTarget`?
* [ ] **3.** If 2., design a proposal how the Hooks representation layer should look like.

### PR DESCRIPTION
**Pull request by mrackwitz**
Closes #3648.

### CODE REVIEW

**Comment by segiddins** [comment]
I don't love that this now makes the `Installer` a part of our public api...

**Comment by mrackwitz** [comment]
It's already part of the public API and commonly used, because the Hooks representation layer is misaligned with what is happening on the installation process.

**Comment by segiddins** [comment]
How is it already part of the public API?

-Samuel E. Giddins

On Jun 7, 2015, at 2:45 PM, Marius Rackwitz <notifications@github.com> wrote:

It's already part of the public API and commonly used, because the Hooks representation layer is misaligned with what is happening on the installation process.

**Comment by mrackwitz** [comment]
By [`InstallerRepresentation#installer`](https://github.com/CocoaPods/CocoaPods/blob/84e84ad5159a618af4e9f253d56f99b1469300a3/lib/cocoapods/hooks/installer_representation.rb#L114-116).

**Comment by segiddins** [comment]
:+1:

**Pull request merged**
