### PR TITLE
Symlink vendored framework headers into the public headers dir

### LINKED ISSUE #3161: Using a pod (which produce framework) in another pod
Hi,
recently Google has updated its pod `Google-Mobile-Ads-SDK`, which now produce a framework. I have a public podspec called `MUKAdMobViewController` which has a dependency to it, and I would like to support new major version.
I paste you podspec:
```
Pod::Spec.new do |s|
  s.name      = 'MUKAdMobViewController'
  s.platform  = :ios, '6.0'
  s.version   = '1.2.4'
  s.summary   = 'View controller which manages an AdMob banner, geolocation and interstitial presentation.'

  s.source = {
    :git => 'https://github.com/muccy/MUKAdMobViewController.git',
    :tag => s.version.to_s
  }
  
  s.requires_arc    = true
  s.source_files    = 'MUKAdMobViewController/*.{h,m}'
  s.compiler_flags  = '-Wdocumentation'
  s.frameworks      = 'CoreLocation'
  
  s.dependency 'Google-Mobile-Ads-SDK', '~> 6.6'
end
```

I bumped up dependency version (`s.dependency 'Google-Mobile-Ads-SDK', '~> 7.0'`) and problems started. I have an example app created to develop `MUKAdMobViewController`.
schermata 2015-02-19 alle 15 45 22

On top you can see two files of my pod: they are actually built by `Pods-MUKAdMobViewController` target, as you know. And that is why header files can not be found. There is no reference to `GoogleMobileAds.framework` there.
schermata 2015-02-19 alle 15 48 06

Before they adopted framework there was no problem. 
Before to post an issue I tried circumvent the problem by setting manually linker flags like `HEADER_SEARCH_PATHS` or `-framework` in `OTHER_LDFLAGS`, but with no success.

How can I do? Thanks.

### PR DESCRIPTION
**Pull request by vincentisambart**
Fixes #3161

### CODE REVIEW

**Comment by vincentisambart** [comment]
As proposed in #3161, it links the headers from vendored frameworks to the public headers directory.
Not perfect, no CHANGELOG entry yet, but first I wanted some feedback.
At first I thought about modifying FRAMEWORK_SEARCH_PATH of each target (adding the frameworks from it dependencies) but it seems that would require some heavy refactoring so I went with the easy solution.

**Comment by neonichu** [comment]
This generally looks good to me, could you please fix the rubocop violations?

**Comment by vincentisambart** [comment]
Thank you.
I fixed the rubocop violations, and updated a CHANGELOG entry.

**Comment by neonichu** [comment]
Awesome, thanks a lot for your contribution, @vincentisambart :tada:

**Comment by mrackwitz** [comment]
>At first I thought about modifying FRAMEWORK_SEARCH_PATH of each target (adding the frameworks from it dependencies) but it seems that would require some heavy refactoring so I went with the easy solution.

In the long run, that won't be a sufficient solution. Publicizing the headers does affect the ability to import headers from Objective-C / clang's tooling, but it won't be possible to use module imports, which makes it harder to use transitive vendored dependencies from Swift pods.

I think for now we are good to go with this solution, but once we solve #1993 and vendored dynamic frameworks are actually working, we will need to implement the more difficult solution.

**Comment by neonichu** [comment]
@mrackwitz you're right, I added a point for this to the task list in #1993

**Pull request merged**
