### PR TITLE
Add .tpp header support

### PR DESCRIPTION
**Pull request by czechboy0**
Added .tpp header support for C++ header files - so that they are symlinked into the Headers directory as well (now they're ignored.)

### CODE REVIEW

**Comment by segiddins** [comment]
Where is this extension used?

**Comment by czechboy0** [comment]
In some C++ projects as a header for template instantiation.

**Comment by segiddins** [comment]
\c @kylef

**Comment by kylef** [comment]
@czechboy0 Would you be able to add an entry to the [CHANGELOG.md](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md)?

**Comment by segiddins** [comment]
It should also probably be added to the list of header extensions in Xcodeproj?

**Comment by czechboy0** [comment]
@kylef Done.
@segiddins Done: https://github.com/CocoaPods/Xcodeproj/pull/241

**Pull request merged**
