### PR TITLE
Prevent crash when configuring schemes for subspecs.

### PR DESCRIPTION
**Pull request by dnkoutso**
Closes https://github.com/CocoaPods/CocoaPods/issues/8880

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Parse scheme configuration for subspecs  
  [dnkoutso](https://github.com/dnkoutso)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by segiddins** [comment]
Please add a test for this change

**Comment by dnkoutso** [comment]
Will do.

**Comment by dnkoutso** [comment]
@segiddins added test, ready for review. Took a different approach given that CocoaPods/Core disallows customization of scheme configurations at the subspec level. It seems we decided to block that due to the fact that subspecs get merged with root spec. 

As I am thinking about this we should probably "revert/change" that decision but not as part of this PR or 1.7.2.

**Pull request merged**
