### PR TITLE
[InfoPlistFile] Include UIRequiredDeviceCapabilities for tvOS pods

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/4514.

- [x] CHANGELOG

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM :+1:

I think we can merge this after changelog entry :)

**Comment by segiddins** [comment]
Will merge when green.

**Comment by nicolasbraun** [comment]
Hello @segiddins 

Will look deeper into this today but has this error yesterday https://i.imgur.com/A4G9wnZ.png
Almost same build passed on November 10th.

Nicolas

**Comment by dcordero** [comment]
@nicolasbraun  Same here. iTC seems to be failing since yesterday for tvOS. With both Cocopods 1.1.1 and 1.2.0.beta.1

https://forums.developer.apple.com/thread/68032

**Comment by segiddins** [comment]
Please open new issues, this PR has been merged for over a year

**Pull request merged**
