### PR TITLE
[repo/push] --use-json to convert podspecs to JSON format when pushing

### PR DESCRIPTION
**Pull request by maschall**
🌈

We use a private repository for podspecs and found that when we changed to 1.0.1 cocoapods we had issues with Ruby DSLs that were old.

Following the trunk, we decided to convert our DSL to JSON format when pushing to our repository.

We thought that others could use the same thing.

### CODE REVIEW

**Comment by orta** [comment]
This works for me, think it's a good idea 👍

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! \nYou can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
    
    
  </tbody>
</table>
  

  

  



Here's an example of your CHANGELOG entry:

```markdown
* [repo/push] --use-json to convert podspecs to JSON format when pushing 
  [maschall](https://github.com/maschall)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by segiddins** [comment]
👍🏻 with a CHANGELOG entry

**Comment by neonichu** [comment]
Hey @maschall, there are a few rubocop errors, see <https://travis-ci.org/CocoaPods/CocoaPods/jobs/140426614#L3353-L3356> — if you could fix them, we can merge :+1: You can use `bundle exec rake rubocop` to see those locally.

**Comment by maschall** [comment]
@neonichu thanks for the heads up and the steps to run locally

**Comment by segiddins** [comment]
Thanks @maschall !

**Pull request merged**
