### PR TITLE
[Installer] Reject installation if a static library is used as a transit...

### PR DESCRIPTION
**Pull request by segiddins**
...ive dependency while integrating Pods as frameworks.

Closes https://github.com/CocoaPods/CocoaPods/issues/2926.

Is there a better way to do this than using `file`?

\c @neonichu @samdmarshall

### CODE REVIEW

**Comment by neonichu** [comment]
In theory, we could use `otool -a` as an alternative, if it has any output => static library. In practice, I wouldn't say it is any better than `file`.

**Comment by kylef** [comment]
You could also just read the file yourself instead of outsourcing to file. The archiver outputs static libraries starting with the `!<arch>\n` as a magic constant at the top.

https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachORuntime/index.html#//apple_ref/c/tag/mach_header_64 outlines the mach_header (and 64bit) for the mach-o file format, including it's 32-bit magic value indicating which variant it is along with the filetype which should have the value of `MH_DYLIB` for dynamic libraries or `MH_OBJECT` if it's intermediate, or even `MH_BUNDLE` if it's a bundle.

**Comment by segiddins** [comment]
What's the benefit of implementing all that, when file tells us the type of file?

**Comment by kylef** [comment]
@segiddins Well, you said "Is there a better way to do this than using..". Not necessarily better, but another approach.

**Comment by samdmarshall** [comment]
I agree with kyle on this, it would be better to parse the file rather than hand it off to another external tool. This should be easy to implement, only thing you would have to watch out for is handling fat static libraries. You would have to check the contained architecture specific binaries in the fat binary file, which would be good because then it would be easy to extract it if necessary.

**Comment by segiddins** [comment]
And all of that seems like a hell of a lot more work, for very little gain.

**Pull request merged**
