### PR TITLE
Do not use `--delete` when copying resources to app target folder

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/CocoaPods/CocoaPods/issues/6927

### CODE REVIEW

**Comment by segiddins** [comment]
Will require an integration specs bump

**Comment by dnkoutso** [comment]
On it.

**Comment by dnkoutso** [comment]
https://github.com/CocoaPods/cocoapods-integration-specs/pull/119

**Comment by dnkoutso** [comment]
Should go green

**Comment by dnkoutso** [comment]
✅

**Comment by nikolaykasyanov** [comment]
Confirmed, build is green: https://travis-ci.org/nikolaykasyanov/CocoaPods13Bug/builds/260678261

**Pull request merged**
