### PR TITLE
[IntegrationSpec] Rebuild for 0.36.0.rc.1

### PR DESCRIPTION
**Pull request by mrackwitz**

### CODE REVIEW

**Comment by segiddins** [comment]
Why is this necessary?

**Comment by mrackwitz** [comment]
Just to bump the version number, it is ignored in the diffs, but still present in files. If I rebuild it for a an intentional change, I want to commit only the intended changes. So by eagerly updating the version number, we ensure to have a cleaner history.

**Comment by segiddins** [comment]
:/ Not really necessary imho, but go ahead and push this sort of non-functional change yourself. No need for a PR.

**Comment by mrackwitz** [comment]
Pushed to master after Travis build succeed.

**Pull request closed without merging**
