### PR TITLE
Fix building of static libs that depend on other libs

### PR DESCRIPTION
**Pull request by themackworth**
This addresses #2747 and #2704.

Integration tests need to be fixed, but I just wanted to get this looked at before I went through all that stuff.  Please let me know if I should reword or move the changelog entry.

### CODE REVIEW

**Comment by themackworth** [comment]
solution based on https://github.com/CocoaPods/CocoaPods/issues/2747#issuecomment-65797551

**Comment by neonichu** [comment]
@themackworth LGTM, once we got the integration specs working, this should be mergeable.

**Comment by mthole** [comment]
Ran into this issue just now. Looking forward to the fix!

**Comment by segiddins** [comment]
@mthole are you saying you've verified this PR fixes things for you?

**Comment by themackworth** [comment]
For what its worth, I tested against https://github.com/themackworth/Cocoapods2704 and https://github.com/lyahdav/cocoapods-issue2704.

I will try to get to the integration tests soon.  If there is anything else in particular you would like me to test against or try, please let me know.

**Comment by mthole** [comment]
@segiddins I hadn't actually tried out this commit when I commented (although I was running into exactly this issue). I've now checked out @themackworth 's branch and used it locally. Can confirm it fixes my issue.

**Comment by neonichu** [comment]
@themackworth Thanks a lot for your contribution, it is highly appreciated! :tada:

**Pull request merged**
