### PR TITLE
Replace [Bool] with [Boolean] in method comments  according to the YARD convention.

### PR DESCRIPTION
**Pull request by jolyot**
This PR is to replace `[Bool]` with `[Boolean]` in method comments.

In the project,  `@param [Boolean]` or `@return [Boolean]` and `@param [Bool]` or `@return [Bool]` are mixed up in the method comments, so the goal is to unify them into `@param [Boolean]` or `@return [Boolean]` according to the [YARD convention](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#literals).

### CODE REVIEW

**Review by dnkoutso — APPROVED** [review]

**Comment by dnkoutso** [comment]
nice thanks! I wanted to do that at some point :) Can you also do one more PR for https://github.com/CocoaPods/Core?

**Comment by dnkoutso** [comment]
Looks like we need to fix CI.

```
Lint : .github#L1
The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287
```

I will do that in another PR now.

**Comment by dnkoutso** [comment]
CI fix here https://github.com/CocoaPods/CocoaPods/pull/10925 @jolyot you will have to rebase shortly once it lands.

**Comment by dnkoutso** [comment]
@jolyot all merged to master. Please rebase this PR so CI can start and we can land this! Thank you!

**Comment by jolyot** [comment]
@dnkoutso 
I rebased this PR. And I opened a related [PR](https://github.com/CocoaPods/Core/pull/706) for https://github.com/CocoaPods/Core

**Comment by dnkoutso** [comment]
Merged core, will merge this one once its green.

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Replace [Bool] with [Boolean] in method comments  according to the YARD convention.  
  [jolyot](https://github.com/jolyot)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
