### PR TITLE
[Installer] Print a post-install message

### LINKED ISSUE #4124: Would be nice to have a "Done" statement after pod install
This is useful when using the Xcode Cocoapods plugin and the output goes to Xcode console, but you don't get a prompt telling you it's done, like on Terminal.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4124.

\c @orta

### CODE REVIEW

**Comment by orta** [comment]
Fab. I liked this function of bundler..

**Comment by orta** [comment]
I'd hit the merge button but it's red, and I'm not sure if I should :dancer:

**Comment by segiddins** [comment]
If you're good with the changes (as demonstrated by the integration spec failures), I'll update the integration specs and merge.

**Pull request merged**
