### PR TITLE
Fix #5291 Issues with compiling C-only source

### LINKED ISSUE #5291: Issues with compiling C-only source in 1.0.0
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

YapDatabase+SQLCipher doesn't compile using CocoaPods 1.0.0. If you upgrade to CocoaPods 1.0.0 and try to compile a simple project using YapDatabase+SQLCipher, you get weird errors compiling yap_vfs_shm.c.

It's because the SQLCipher umbrella header includes UIKit.h, and then is included in a C-only file in another Pod. It should conditionally include UIKit based on language.

More information is here:

https://github.com/yapstudios/YapDatabase/issues/322#issuecomment-218535586

### PR DESCRIPTION
**Pull request by chrisballinger**
It appears to fix my issues compiling YapDatabase/SQLCipher.

### CODE REVIEW

**Comment by segiddins** [comment]
👍 with a CHANGELOG entry and fixed tests

**Comment by jafara** [comment]
@chrisballinger are you planning on finishing this PR? I just hit this problem...

**Comment by chrisballinger** [comment]
I haven't had time to get the tests to pass, but it otherwise works. The tests have some hardcoded values that are no longer valid with the new output. For now I've been sticking with 0.39 because this wasn't the only issue I encountered.

**Comment by dnkoutso** [comment]
This should be closed now since https://github.com/CocoaPods/CocoaPods/pull/5844 landed.

**Pull request closed without merging**
