### PR TITLE
Rcproject source files

### PR DESCRIPTION
**Pull request by parallaxe**
RealityComposer-projects (rcproject) are bundles that must be compiled. Thus, it is necessary to declare them in the resources-spec but also to add them to the compile-stage.

### CODE REVIEW

**Comment by parallaxe** [comment]
It fails the tests
`Pod::Command::Repo::Update - excludes the spec-repo from Time Machine backups` and `#exclude_from_backup - excludes the dir from Time Machine backups`. Both relate to Time Machine and don't fail on my local machine (which also runs on macOS 10.15). And I don't see how my changes could have a side-effect related to these tests. 
Any ideas?

**Comment by igor-makarov** [comment]
@parallaxe Could you please rebase on `master`?

**Comment by parallaxe** [comment]
> @parallaxe Could you please rebase on `master`?

Sure, sorry 😅 

The linter-errors are

```
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb:7:9: C: Block has too many lines. [1483/1476]
        describe PodTargetInstaller do ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/unit/installer/xcode/pods_project_generator/pod_target_installer_spec.rb:8:11: C: Block has too many lines. [1481/1476]
          describe 'In General' do ...
          ^^^^^^^^^^^^^^^^^^^^^^^^
```

The maximum of 1476 sounds quite arbitrary - should I adopt the rubocop-rule? If yes, what should the number be?

**Comment by igor-makarov** [comment]
I believe this rule should be excluded for `'spec/**'`, @segiddins WDYT?

**Comment by segiddins** [comment]
I think we've disabled a bunch of those metrics rules already, I'm 100% ok with disabling this one

**Comment by igor-makarov** [comment]
@segiddins https://github.com/CocoaPods/CocoaPods/pull/10483

**Comment by igor-makarov** [comment]
@parallaxe could you please rebase? This will unblock the linter error.

**Comment by parallaxe** [comment]
Looks good? 🙂

**Comment by parallaxe** [comment]
Anything that's missing? Anything I can do to get it merged?

**Comment by parallaxe** [comment]
@igor-makarov Anything left I should do?

**Comment by dnkoutso** [comment]
@parallaxe you need to rebase this PR again as it contains another commit thats not meant to be the change you want.

**Comment by dnkoutso** [comment]
superseded by https://github.com/CocoaPods/CocoaPods/pull/10793 closing this one due to inactivity and will land the other one instead including credit to the original author.

**Pull request closed without merging**
