### PR TITLE
Use `require` for MachO instead of `autoload`

### PR DESCRIPTION
**Pull request by amorde**
Closes https://github.com/CocoaPods/CocoaPods/issues/7867

### CODE REVIEW

**Comment by segiddins** [comment]
This shouldn't be necessary.... `autoload` calls `require` under the hood when `const_missing` is called with the given constant

**Comment by amorde** [comment]
@segiddins any insights on why this change fixes the issue for multiple people then? I agree it _shouldn't_ be necessary but quite a few people are having this crash

**Comment by segiddins** [comment]
It’s possible their ruby environment is in a weird state

**Comment by amorde** [comment]
I do think it's worth it if it can fix the issue for a lot of people but if you disagree I'll close this.

**Comment by segiddins** [comment]
Up to you

**Comment by amorde** [comment]
Let's get it into the 1.6.0 beta and we can revert if it impacts start up time or causes other issues

**Comment by amorde** [comment]
I also don't know enough about autoload vs require (I did do a bit of research into it) to know how this could be breaking for anyone

**Comment by icecrystal23** [comment]
I manually replaced autoload with require and that worked for me locally, too.

**Comment by amorde** [comment]
@icecrystal23 this was included in the 1.6.0.beta.1 release

**Comment by icecrystal23** [comment]
Was it? Because I had to fix it manually after installing 1.6.0.beta.1
I'm not 100% sure I'm running the beta even though I installed it, though.  Do I have to call it differently or anything? pod --version is still telling me 1.5.3

**Pull request merged**
