### PR TITLE
Bump minimum Xcodeproj gem version to 1.15.0

### PR DESCRIPTION
**Pull request by revolter**
Needed for this: https://github.com/CocoaPods/Xcodeproj/pull/706

### CODE REVIEW

**Comment by dnkoutso** [comment]
@revolter we dont strictly need it do we? The requirement accepts `>= 1.14.0`. Is there a new feature in 1.15.0 that CocoaPods needs in order to function?

**Comment by revolter** [comment]
Yes, the one I linked in the description.

**Comment by revolter** [comment]
Oh, so running `bundle update cocoapods` will also update `Xcodeproj` to `1.15.0`, without this PR?

**Comment by dnkoutso** [comment]
Yes! because CocoaPods accepts anything Xcodeproj 1.14.0 and above.

Its harmless to land this but we dont strictly need it because we do not use something new that is required.

**Comment by revolter** [comment]
Then I say we should close this, as it's not strictly needed, as you said, and could be confusing in the future.

**Comment by dnkoutso** [comment]
SGTM!

**Comment by dnkoutso** [comment]
@revolter you can just run `bundle update xcodeproj` btw.

**Comment by revolter** [comment]
Oh, even if it's not in my `Gemfile`? (only `cocoapods` is in my `Gemfile`)

**Comment by dnkoutso** [comment]
Even prior versions should continue to work btw as they accept `>=`.

Yes `bundle update xcodeproj` should work.

**Pull request closed without merging**
