### PR TITLE
[Generator::Plist] Ensure a CFBundleVersion is set for resource bundles

### LINKED ISSUE #4897: Unable to load xcassets from bundle when using frameworks.
This issue is a follow up to issue [#4851](https://github.com/CocoaPods/CocoaPods/issues/4851), as requested by @segiddins and @efirestone.

My CocoaPod [(ASMessenger, pre-release)](https://github.com/asharma-atx/ASMessenger) is unable to load xcassets from it's bundle when the Podfile specifies that it should `use_frameworks!`. It is able to load the image assets if it is being used as a static library.

I'm able to log out the bundle (see below) but it seems that there are no images in the bundle (viewing the bundle contents in Finder does not reveal any xcassets). For that reason, I suspect that the image assets are simply not being copied into the bundle.

`NSLog(@"Bundle %@", bundle);` logs out this:
```
bundleTest[5637:1947336] Bundle: NSBundle </var/containers/Bundle/Application/20071A5C-738C-429B-81DC-6CE9B0C1B882/bundleTest.app/Frameworks/ASMessenger.framework/ASMessenger.bundle> (not yet loaded)
```

You can grab a copy of the source [here](https://github.com/asharma-atx/ASMessenger). The image is being used in the class ASAttachmentCell on line 67. 

**Important Note:** You'll need to add the `use_frameworks!` flag to the Podfile to reproduce the issue. If you accidentally install the app before you do this, please be sure to clear out the old bundle before your add `use_frameworks!` and redo the pod install, or you may still be working with the static library bundle (which works fine).  

Here is the setup:

Podspec:
`s.resource_bundles = { 'ASMessenger' => ['Pod/Assets/**/*'] }`

Resources path in project directory:
`ASMessenger > Pod > Assets`

How I'm accessing the bundle:
```
+ (instancetype)ASMessengerBundle{
    
    // TODO: Resolve issue preventing assets from being bundled if CocoaPod is being used as a framework.
    
    static NSBundle *bundle = nil;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        NSBundle *containingBundle = [NSBundle bundleForClass:[ASEntry class]];
        NSURL *bundleURL = [containingBundle URLForResource:@"ASMessenger" withExtension:@"bundle"];
        
        if (bundleURL) bundle = [NSBundle bundleWithURL:bundleURL];
    });
    
    return bundle;
}
```

How I'm _trying_ the accessing the image:

`[UIImage imageNamed:@"detail_arrow.png" inBundle:[NSBundle ASMessengerBundle] compatibleWithTraitCollection:nil];`

Details:
- CocoaPods 1.0.beta.3

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4897.

I believe the integration spec failure here will act as sufficient test coverage for this.

### CODE REVIEW

**Comment by mrackwitz** [comment]
Can't we instead set the pods project `CURRENT_PROJECT_VERSION` to a fixed value, which will be inherited to bundle targets?

**Comment by segiddins** [comment]
@mrackwitz we got rid of setting the `CURRENT_PROJECT_VERSION` for some product types before and I'm worried about introducing a regression 😁

**Comment by mrackwitz** [comment]
@segiddins: Oh, okay didn't had that in mind. Then this good to go from my side. :+1:

**Comment by neonichu** [comment]
LGTM :+1:

**Comment by segiddins** [comment]
Should finally be good to merge, sorry for the delay!

**Comment by segiddins** [comment]
Failure is spurious

**Pull request merged**
