### PR TITLE
Build samples with Xcode 14.2, fix resource bundle code signing issue

### PR DESCRIPTION
**Pull request by dnkoutso**
closes https://github.com/CocoaPods/CocoaPods/issues/11402

integration specs: https://github.com/CocoaPods/cocoapods-integration-specs/pull/338

### CODE REVIEW

**Review by zadr — APPROVED** [review]

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Build samples with Xcode 14.2, fix resource bundle code signing issue  
  [dnkoutso](https://github.com/dnkoutso)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by justinseanmartin — APPROVED** [review]

**Comment by ykhandelwal913** [comment]
@dnkoutso When milestone 1.12.0 will be released? There are lots of enhancement done in this milestone which is going to fix some of the issues as a developer we are facing.

**Comment by dnkoutso** [comment]
I am shipping a release today.

**Comment by dnkoutso** [comment]
shipped.

**Pull request merged**
