### PR TITLE
[Validator] Add private mode

### PR DESCRIPTION
**Pull request by segiddins**
Depends upon https://github.com/CocoaPods/Core/compare/seg-linter-private-mode.
Closes https://github.com/CocoaPods/Core/issues/190.
Closes https://github.com/CocoaPods/CocoaPods/issues/2682.

\c @orta, @kylef

### CODE REVIEW

**Comment by segiddins** [comment]
@kylef please remind me what I need to do?

**Comment by segiddins** [comment]
@kylef ?

**Comment by segiddins** [comment]
Ping @kylef

**Comment by kylef** [comment]
@segiddins needs rebasing

**Comment by segiddins** [comment]
beyond that?

**Comment by Ashton-W** [comment]
Very interested in seeing this get merged

**Comment by segiddins** [comment]
@Ashton-W on my list of things to do

**Comment by segiddins** [comment]
Re-written. Please review this and the Core branch, @CocoaPods/core !

**Comment by neonichu** [comment]
LGTM :+1:

**Comment by mrackwitz** [comment]
I think, we can improve the wording of the hint message. We should explain when you can actually ignore the errors. e.g:
>All results apply only to public specs. (But you can use `--private` to ignore them, if you're linting a spec for a private repo.)

**Comment by segiddins** [comment]
Will merge when travis has run.

**Pull request merged**
