### PR TITLE
Add flag to ignore prerelease versions when reporting latest version for outdated pods

### PR DESCRIPTION
**Pull request by cltnschlosser**

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Add flag to ignore prerelease versions when reporting latest version for outdated pods  
  [cltnschlosser](https://github.com/cltnschlosser)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
This should really be the opposite way around, it shouldn't tell you prerelease versions in outdated unless you explicitly request them IMO

**Comment by cltnschlosser** [comment]
> This should really be the opposite way around, it shouldn't tell you prerelease versions in outdated unless you explicitly request them IMO

I agree, just did it this way, to keep the behavior without a flag passed the same. Fine with changing it if that's what people want.

**Comment by orta** [comment]
Hrm, good point - it's been this way for 6 years. It does feel like an accident though. I'm not gonna block the PR on it though.

**Comment by cltnschlosser** [comment]
@dnkoutso You seem to be the person to bug to get things merged. Thoughts on this?

**Comment by dnkoutso** [comment]
@cltnschlosser I just released 1.10.0 stable can you rebase this to fix the changelog entry to be in the right spot?

Thanks! I can merge after.

**Comment by cltnschlosser** [comment]
@dnkoutso Done and CI passed.

**Review by dnkoutso — APPROVED** [review]

**Comment by dnkoutso** [comment]
thanks!

**Pull request merged**
