### PR TITLE
Remove target environment header entirely

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/2390, but I'm not really sure if this is what @fabiopelosin wanted.

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM :+1:

**Comment by mrackwitz** [comment]
:heart:

**Comment by segiddins** [comment]
Is this really something we want to do, though?

**Comment by neonichu** [comment]
:+1: better break before 1.0 :)

**Comment by mrackwitz** [comment]
Is this something, which we want to keep alive in a plugin?

**Comment by segiddins** [comment]
@mrackwitz nah, since most of the use would be to other library authors.

**Comment by orta** [comment]
A GitHub search for both `COCOAPODS_POD_AVAILABLE` and `COCOAPODS_VERSION_MAJOR` turns up nothing, I once talked about the pods available in an issue but I'm not sure if they're being used at all. Think it's fine to remove.

**Comment by segiddins** [comment]
Cool, will polish this tomorrow!

**Comment by orta** [comment]
Well, I have to do some work at least https://github.com/dblock/ios-snapshot-test-case-expecta/issues/17

**Comment by segiddins** [comment]
This should now be mergable!

**Comment by neonichu** [comment]
Rerunning Travis just to be safe, then I'll merge

**Comment by mrackwitz** [comment]
Thanks! :+1: Unblocks #3550 for me.

**Comment by gregcotten** [comment]
Hey! I use COCOAPODS_POD_AVAILABLE and COCOAPODS_VERSION_MAJOR

What gives?

**Comment by gregcotten** [comment]
@orta Github search doesn't work that way. You can't just search for a partial word, unfortunately. Since people will be using "COCOAPODS_VERSION_MAJOR_(PODNAME HERE)" rather than "COCOAPODS_VERSION_MAJOR" of course "COCOAPODS_VERSION_MAJOR" returns no results.

**Comment by matteonovelli** [comment]
I also used this feature ;(

**Comment by segiddins** [comment]
@matteonovelli this PR is closed, it was merged months ago.

**Comment by matteonovelli** [comment]
Yes, I know. I recently updated Cocoapods and I have noticed. I still think it was very helpful. 
But don't worry about you made a very grat work!

**Pull request merged**
