### PR TITLE
mark_ruby_file_ref add indent width and tab width config

### PR DESCRIPTION
**Pull request by dacaiguoguogmail**
Use 2 space indentation from ruby guide

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* mark_ruby_file_ref add indent width and tab width config  
  [dacaiguoguogmail](https://github.com/dacaiguoguogmail)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by amorde** [comment]
Nice! Can you update the tests to include this change?

https://github.com/CocoaPods/CocoaPods/blob/528d7973a6bc9b8d4917c355a9c75b5a54b32bc9/spec/unit/project_spec.rb#L250-L257

**Comment by amorde** [comment]
also probably worth a changelog since this is a noticeable change

**Comment by dnkoutso** [comment]
Agreed

**Comment by dacaiguoguogmail** [comment]
Already add tests and write change to CHANGELOG.md

**Pull request merged**
