### PR TITLE
Fix globbing to traverse symlinks

### LINKED ISSUE #6603: Pathname.glob() doesn't traverse symlinks
* [x] Using latest cocoapods (1.2.0)
* [x] Using Xcode 8.3 latest
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Pathname.glob() in ruby doesn't traverse symlinks and thus results in broken integrations with Pods that use symlinked sources.

I can't confirm if this is an issue for remotely downloaded pods but this is an issue for local pods referenced via `pod 'SnapKit', path: 'Podspecs/'`.

We use a mono-repo and include all dependencies locally so I've created a custom Podspec for every dependency. We use `Podspecs/<ModuleName>.podspec` to house the specs while we keep the sources in `Vendor/<ModuleName>`

Because Cocoapods requires the `source_files` path to not be absolute and not traverse upwards in the file system we symlink the `Vendor` directory into the `Podspecs` directory.

With the symlink no pod will install because Cocoapods never traverses the sources. If we use a copy it works fine.

I got to digging in the Ruby code and found the exact place where the difference in path resolving occurs. In `path_list.rb` around line 50 there is `Pathname.glob(escaped_root + '**/*', File::FNM_DOTMATCH).lazy`. For some reason the evaluation of the globbing results in a shallow traversal for symlinks.

https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/sandbox/path_list.rb#L55

## What did you do?

`pod install`

## What did you expect to happen?

Pods to be installed

## What happened instead?

Cocoapods finds no sources and installs no pods

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.3 (8E162)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/var/rbenv/versions/2.3.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 17ac6640821fe1fed0ef5159d7765662bd0a3653
               master - https://github.com/CocoaPods/Specs.git @ 6d1a8a522209bc650a62b09d7b69521419b9c14e
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 2.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'SymlinksFailure' do
    pod 'SnapKit', path: 'Podspecs/'
end
```

## Project that demonstrates the issue

[SymlinksFailure.zip](https://github.com/CocoaPods/CocoaPods/files/880752/SymlinksFailure.zip)

### PR DESCRIPTION
**Pull request by robertjpayne**
This adjusts the globbing to ensure it traverses symlinks and also then cleans up some extra invalid paths it adds as a result of that.

I apologise I'm a bit short on time but need to write a spec that ensure we don't break symlink traversing in the future.

Fixes #6603

### CODE REVIEW

**Comment by dnkoutso** [comment]
Yes a spec would be good here. Thanks for this.

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix globbing to traverse symlinks 
  [robertjpayne](https://github.com/robertjpayne)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by robertjpayne** [comment]
@dnkoutso is it just me or is Travis completely broken? The failing reason seems entirely unrelated.

**Comment by dnkoutso** [comment]
@robertjpayne I see failures here https://travis-ci.org/CocoaPods/CocoaPods/jobs/216600484

**Comment by robertjpayne** [comment]
@dnkoutso ah! ok I'll check that out too and see what's up

**Comment by dnkoutso** [comment]
@robertjpayne any plans on completing this?

**Comment by robertjpayne** [comment]
@dnkoutso I was/am still awaiting feedback on the original issue #6603 

Path traversing is just a total mess and fixing this breaks how frameworks are copied and embedded. I'm really unsure how best to resolve it.

**Comment by dnkoutso** [comment]
@robertjpayne can you try https://github.com/CocoaPods/CocoaPods/pull/7051 perhaps? I think it supersedes this PR now.

**Comment by amorde** [comment]
Wasn't sure how to add a commit to this PR, otherwise would have done so. Sorry!

**Comment by dnkoutso** [comment]
Going to close this PR in favor of https://github.com/CocoaPods/CocoaPods/pull/7051

**Pull request closed without merging**
