### PR TITLE
Just remove write permissions from files, so executables are unaffected

### LINKED ISSUE #3501: [0.37.0] Framework executable permissions are incorrect
Regression in 0.37, everything works fine under 0.36.4.
The permissions for _CrashlyticsFramework_ are incorrect and the build fails with

```
...ommitted../ios-build/build/App.build/Automation-iphoneos/AppTarget.build/Script-awesome.sh: line 3: ./Pods/CrashlyticsFramework/Crashlytics.framework/run: Permission denied
```

```
~/workspace/ios-build/Pods/CrashlyticsFramework/Crashlytics.framework $ l
total 1336
drwxr-xr-x  9 jenkins  _assetcache     306 May  4 16:48 .
drwxr-xr-x  5 jenkins  _assetcache     170 May  4 16:48 ..
lrwxr-xr-x  1 jenkins  _assetcache      28 May  4 16:48 Crashlytics -> Versions/Current/Crashlytics
lrwxr-xr-x  1 jenkins  _assetcache      24 May  4 16:48 Headers -> Versions/Current/Headers
drwxr-xr-x  3 jenkins  _assetcache     102 May  4 16:48 Modules
lrwxr-xr-x  1 jenkins  _assetcache      26 May  4 16:48 Resources -> Versions/Current/Resources
drwxr-xr-x  4 jenkins  _assetcache     136 May  4 16:48 Versions
-r--r--r--  1 jenkins  _assetcache  253984 May  4 16:48 run
-r--r--r--  1 jenkins  _assetcache  412960 May  4 16:48 submit
```

### PR DESCRIPTION
**Pull request by mglidden**
Fixes #3501

### CODE REVIEW

**Comment by dbarden** [comment]
Fixes #3513 as well

**Comment by kylef** [comment]
Thanks for the contribution @mglidden, this has already been fixed in master via https://github.com/CocoaPods/CocoaPods/pull/3506.

**Comment by segiddins** [comment]
No, this PR fixes something different.

**Comment by segiddins** [comment]
:+1:

**Comment by mglidden** [comment]
Yup, we'll need this change as well. I fixed the merge conflicts, so we should be good to go.

**Comment by segiddins** [comment]
Thanks so much @mglidden !

**Comment by kylef** [comment]
My bad, sorry about this. I was looking at the documentation for `file?` and it mentions "regular file" which isn't properly defined, I assumed meant non-executable.

> Returns true if the named file exists and is a regular file

**Comment by segiddins** [comment]
Regular file in this case means non directory and non symlink, iirc

-Samuel E. Giddins

On May 6, 2015, at 9:00 AM, Kyle Fuller <notifications@github.com> wrote:

My bad, sorry about this. I was looking at the documentation for file? and it mentions "regular file" which isn't properly defined, I assumed meant non-executable.

Returns true if the named file exists and is a regular file

**Comment by dbarden** [comment]
Just a really quick note on symlinks:

> If the file argument is a symbolic link, it will resolve the symbolic link and use the file referenced by the link

**Pull request merged**
