### PR TITLE
Changed the default template Podspec description to be a comment.

### LINKED ISSUE #3883: Default Podfile summary and description fields
I wanted to just start a discussion about this really before even thinking about writing any code or making any changes.

I spend a fait bit of time looking through new pods and the number of times I see this is quite surprising:

default-description

I'd like to write a small patch to reduce the chances of this happening. If the default text for the summary and description fields generated by pod create were to be moved to be comments above the fields rather than the content of the fields that it would force people to put at least a little thought into what they were submitting.

Lint doesn't allow a blank summary, or a description which is shorter than the summary so it would *force* user written responses to both those fields before a pod could be submitted.

I understand that the recent quality index changes will mean that those badly described pods will not get much visibility. However, think about it from the perspective of the pod author. If they took the time to create a podspec, that's a step they took to make their code available or give it some visibility. Allowing these boilerplate fields to be submitted means that the path of least resistance is simply not to do anything and they hurt their pod before it even gets started.

Thoughts?

### PR DESCRIPTION
**Pull request by daveverwer**
Fixes #3883.

### CODE REVIEW

**Comment by segiddins** [comment]
If this is something we decide to merge, we'll also need to update https://github.com/CocoaPods/pod-template

**Comment by orta** [comment]
I think this is a much better idea, I'm definitely a :+1:  for it

**Comment by orta** [comment]
Thanks @daveverwer :+1: - @segiddins I'll update the pod-template now.

**Comment by segiddins** [comment]
<3 both of you!

**Comment by daveverwer** [comment]
Thanks!

**Pull request merged**
