### PR TITLE
Update `pod init` for 1.0

### PR DESCRIPTION
**Pull request by orta**
I did some [testing](https://github.com/CocoaPods/CocoaPods-app/pull/277) on our App's `pod init` and spotted a few minor issues at CocoaPods level.

screen shot 2016-04-06 at 06 51 48

### CODE REVIEW

**Comment by k0nserv** [comment]
LGTM :+1:

**Comment by jcampbell05** [comment]
LGTM :)

**Comment by neonichu** [comment]
:+1:

**Comment by segiddins** [comment]
This still doesn't handle target inheritance and all that jazz (and I believe it might still have exclusive in there) so it's not entirely updated, but it's an improvement

**Comment by orta** [comment]
Good point, I can improve

**Comment by segiddins** [comment]
@orta no worries -- we can merge this as-is and leave https://github.com/CocoaPods/CocoaPods/issues/4714 to track the remainder if you'd like

**Comment by orta** [comment]
Agree, let's do that :+1:

**Pull request merged**
