### PR TITLE
Handle CoreData mapping model resources

### PR DESCRIPTION
**Pull request by efirestone**
When using recursive resource globs, CoreData mapping models should not have their child items added to the project directly.

### CODE REVIEW

**Comment by efirestone** [comment]
This was the last resource that's specially handled by the copy-resources build phase script, so I believe it's the only one that was missing.

**Comment by segiddins** [comment]
:+1: with a rebase

**Comment by segiddins** [comment]
Thanks so much @efirestone !

**Comment by efirestone** [comment]
Happy to help!

**Pull request merged**
