### PR TITLE
[Installer] Make use of 'Boolean' consistent in docs

### PR DESCRIPTION
**Pull request by DanToml**

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* [Installer] Make use of 'Boolean' consistent in docs 
  [DanToml](https://github.com/DanToml)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
👍

**Comment by DanToml** [comment]
I don't think this needs a changelog entry?

**Comment by orta** [comment]
IMO, not really but will let @segiddins make that call

**Comment by segiddins** [comment]
Nah doc updates don't require changelog entries

**Pull request merged**
