### PR TITLE
[WIP] Attempt fix 10430

### PR DESCRIPTION
**Pull request by dnkoutso**
Maybe closes https://github.com/CocoaPods/CocoaPods/issues/10430

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* [WIP] Attempt fix 10430  
  [dnkoutso](https://github.com/dnkoutso)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
integration tests will fail but I am curious on examples if they are passing.

**Comment by dnkoutso** [comment]
ok good examples pass with this change.

will chat offline to see if this is the right fix after I understand our scripts more and if this change might cause any regressions.

**Comment by dnkoutso** [comment]
talked offline, we should not do this despite the fact the examples passed.

**Pull request closed without merging**
