### PR TITLE
[SpecsState] Ensure only root names are stored

### LINKED ISSUE #4821: Pods update binds to commit
Since migrating to version 1.0.0.beta2 I've experiencing this behaviour where `pod update` doesn't track the branch but instead binds itself to a commit

Podfile extract:

```
...
  pod 'OneTapKit/Application',:git => 'git@github.com:receipt-bank/onetap-ios-kit.git', :branch => 'feature/schedule-tasks'
...
```

output of `pod update`
```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OneTapKit` from `git@github.com:receipt-bank/onetap-ios-kit.git`, commit `667468e504fe1a6a0516552d15ec082d5d5aee69`
```

expected output would be:
```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OneTapKit` from `git@github.com:receipt-bank/onetap-ios-kit.git`, branch `feature/schedule-tasks`
```

resulting Podfile.lock (extract)
```
PODS:
 ...
  - OneTapKit/Application (0.1.4.dev):
    - OneTapKit/Core
  - OneTapKit/Core (0.1.4.dev):
    - Alamofire (~> 3.1.0)
    - Bolts/Tasks (~> 1.5)
    - RBCamera/Storage (~> 0.2.0)
    - XCGLogger (~> 3.2)
 ...

DEPENDENCIES:
 ...
  - OneTapKit/Application (from `git@github.com:receipt-bank/onetap-ios-kit.git`, branch `feature/schedule-tasks`)
  - RBCamera (from `git@github.com:receipt-bank/RBCamera.git`, branch `master`)
  ...

EXTERNAL SOURCES:
  OneTapKit:
    :branch: feature/schedule-tasks
    :git: git@github.com:receipt-bank/onetap-ios-kit.git
 ...

CHECKOUT OPTIONS:
  OneTapKit:
    :commit: 667468e504fe1a6a0516552d15ec082d5d5aee69
    :git: git@github.com:receipt-bank/onetap-ios-kit.git
 ...

SPEC CHECKSUMS:
  ...
  OneTapKit: 86eb5285e5f2852d311abaff90e430fe2157dc16
  ...

PODFILE CHECKSUM: 19995f659101d08bf1051a1e30d95133e439fef6

COCOAPODS: 1.0.0.beta.2
```

I've tried changing the podspec version but it still won't cause pod update the fetch the head of the branch. Only way to make pod update work as expected after the initial install/update (short of wiping Podifle.lock and Manifest.lock) is to remove the pod entries from `CHECKOUT OPTIONS`.

### PR DESCRIPTION
**Pull request by segiddins**
Fixes #4821.

\c @sciutand

- [x] CHANGELOG
- [x] Specs

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM :+1:

**Comment by mrackwitz** [comment]
With that change the attributes of `SpecState` would better serve their purpose as sets I guess?

**Comment by segiddins** [comment]
@mrackwitz yeah, probably. I'll make that change.

**Comment by segiddins** [comment]
Done, uses a set now.

**Pull request merged**
