### PR TITLE
Do not pass code-sign arguments for OS X targets.

### LINKED ISSUE #3310: Pushing podspec fails in 0.36 for OSX resource bundle.
I have a podspec for a library which supports OSX and iOS and contains a resource bundle which is used on both platforms.  Recently, when trying to push a new version to our private spec repo (`pod repo push <repo> <podspec>`), the OSX version has failed when validating the resource bundle:

```
/usr/bin/codesign --force --sign - /var/folders/6j/4__tztjj7j3_gn_4bjmsvzq8000253/T/CocoaPods/Lint/build/Release/SquareCoreResources.bundle
/var/folders/6j/4__tztjj7j3_gn_4bjmsvzq8000253/T/CocoaPods/Lint/build/Release/SquareCoreResources.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
```

This works fine with CocoaPods 0.35, but is a new issue with 0.36.  The pod is installed and built into it's local example project just fine.  I know some changes went into 0.36 with fixed another bug with resource bundles, maybe this is a side effect?

For reference here's the spec:

```
Pod::Spec.new do |s|
  s.name         = "SquareCore"

#snip
  
  s.ios.deployment_target = "7.0"
  s.osx.deployment_target = "10.8"
  
#snip
  
  s.resource_bundle = { "SquareCoreResources" => ["Resources/SquareCoreResources/*"]}
}
```

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #3310

### CODE REVIEW

**Comment by segiddins** [comment]
:+1: presuming the tests pass

**Comment by brianpartridge** [comment]
Ack, just realized that this hasn't shipped yet because it landed in master rather that 0.36.*.

**Comment by kylef** [comment]
@brentnycum It has, there is a 0.37.0.beta.1. The 0.36.4 is only supposed to have xcasset related changes.

**Comment by brianpartridge** [comment]
Upgrading to the beta now. Thanks.

**Pull request merged**
