### PR TITLE
[ISSUE_TEMPLATE] Make sections collapsible

### PR DESCRIPTION
**Pull request by mrackwitz**
/c @orta

### CODE REVIEW

**Comment by orta** [comment]
Interesting, when I go to the page for this, it all seems really unreliable WRT what it shows

https://github.com/CocoaPods/CocoaPods/blob/5b55147aee9eec8b71dee2bf4ff3f9dad3b6a09b/.github/ISSUE_TEMPLATE.md

**Comment by mrackwitz** [comment]
How do you mean unreliable? The first section with instructions should be collapsed by default, while all others are expanded by default.

**Comment by orta** [comment]
The behavior of the open/closing is unpredictable:

**Comment by orta** [comment]
I bet it needs the `<summary>`  - http://www.w3schools.com/tags/tag_details.asp / https://gist.github.com/orta/057eab0832773aa299a6ebd39187ab06

**Comment by mrackwitz** [comment]
Okay, that seems to be more a general rendering issue by the browser, maybe that's caused by skipping the `<summary>` element? I'm unable to reproduce that locally. Which browser do you use?

**Comment by orta** [comment]
I'm on Safari on the `10.11.6 Beta (15G19a)`

**Comment by mrackwitz** [comment]
Well as that primarily affect us as developers, we should defer this change at least until the beta is fixed. I looked into the WebKit bugtracker, but didn't found anything related. Maybe worth a radar.

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
Checked again, still inconsistent behaviour on on Safari

**Comment by orta** [comment]
Took another look, still hanky - gonna close this, thanks for trying @mrackwitz 👍

**Pull request closed without merging**
