### PR TITLE
Revert "Use ${SRCROOT} rather than ${PODS_ROOT} in the generated mani…

### PR DESCRIPTION
**Pull request by dnkoutso**
…fest lock script phase."

This reverts commit 8c4b4d92a798515d7f4dce3ac8655e280fd19971.

### CODE REVIEW

**Comment by segiddins** [comment]
Add a comment or test so we don't end up making the same change again?

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Revert "Use ${SRCROOT} rather than ${PODS_ROOT} in the generated mani… 
  [dnkoutso](https://github.com/dnkoutso)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dnkoutso** [comment]
The problem is that if you have 2 xcodeprojects and one is nested then this breaks.

Main.xcodeproj
SubDirectory/Another.xcodeproj

Then this phase fails on Another.xcodeproj because $(SRCROOT) is wrong. Any ideas @segiddins ?

**Comment by dnkoutso** [comment]
May have a better solution for this.

**Pull request closed without merging**
