### PR TITLE
Ask user to run 'pod install' when a resource to copy not found

### PR DESCRIPTION
**Pull request by manuyavuz**
Shows an error message in Xcode like the following:

```
Resource "RESOURCE_PATH" not found. Run 'pod install' to update the copy resources script.
```

### CODE REVIEW

**Comment by manuyavuz** [comment]
@segiddins, travis fails because of the integration specs. We also need to update them.

**Comment by segiddins** [comment]
👍🏻

**Comment by orta** [comment]
nice thinking

**Comment by manuyavuz** [comment]
I think I can't merge it myself because tests does not pass. I'm leaving this to you @segiddins :)

**Comment by segiddins** [comment]
@manuyavuz update the integration specs, push those, push to this PR, then merge :)

**Comment by manuyavuz** [comment]
Done!

**Comment by dnkoutso** [comment]
@manuyavuz @segiddins I am hitting this with the latest master SHA.

Is the build phase removed entirely or do we need to de-integrate/integrate again for an updated script?

**Comment by segiddins** [comment]
Please open a new issue being more specific -- this is a merged PR, so I'm not really sure what you mean by "hitting this"

**Pull request merged**
