### PR TITLE
Fix validation when using --swift-version

### LINKED ISSUE #6941: passing --swift-version still throws error message as though it wasn't passed
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint --swift-version=4.0` with no `.swift-version` file.

## What did you expect to happen?

Library lints with Swift 4.0 and doesn't complain about it, or if it does, gives a more useful error message.

## What happened instead?

``` -> BonMot (4.3.1)
    - WARN  | [iOS] swift_version: The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`

```

### Stack

```
   CocoaPods : 1.3.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9M202q)
         Git : git version 2.14.0
Ruby lib dir : /Users/igeek/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8ee4d9d7c2a9e2b74a8a7856ca40ddc78f279672
```

### Installation Source

```
Executable Path: /Users/igeek/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Check out this branch and delete the `.swift-version` file: https://github.com/Raizlabs/BonMot/tree/feature/xcode-9

### PR DESCRIPTION
**Pull request by DanToml**
Closes #6941

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix validation when using --swift-version  
  [DanToml](https://github.com/DanToml)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
👍

**Comment by dnkoutso** [comment]
Rubocopster

**Comment by iDevelopper** [comment]
??

**Comment by dnkoutso** [comment]
Was just saying that rubocop was sad or this PR.

**Pull request merged**
