### PR TITLE
[README] CocoaPods.app badge

### PR DESCRIPTION
**Pull request by nwest**
Initially I added "A full-featured and standalone installation of CocoaPods for OS X." But that causes the X at the end to newline. Thoughts on this? Should something go in the Info column?

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="true"><code>fit</code> left in tests (README.md)</td>
    </tr>
    
    
  </tbody>
</table>
  

  

  




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by nwest** [comment]
I realized we could just link to the app's landing page for info.

**Comment by orta** [comment]
This looks like a great idea 👍

**Pull request merged**
