### PR TITLE
fix issue #3967

### PR DESCRIPTION
**Pull request by christyuj**
#3967 Prevent if the framework's headers is nil
because our company's app has a lot of team building at the same moment ,so we do not want other team's framework use our team's framework.if not necessery, we do not let framework with headers (in some case we will, but the headers include just protocol but not class).

### CODE REVIEW

**Comment by segiddins** [comment]
Please add some tests for the issue you're fixing, and have a look at the test failures on CI? Thanks!

**Comment by christyuj** [comment]
thanks for segiddins, it is my first time commit for this project, i will run bundle exec rake in local now, thanks again ~

**Comment by christyuj** [comment]
now i want to put some test in specs but .... i  can not put BananaNoHeaderLib to the git to test...

**Comment by christyuj** [comment]
i add the test but i can't see the travis CI 's details....how can i know where i was wrong .
now i do nothing and checkout the code from CocoaPods master... i still find 15 error in local . it seem like that  i use my company pod-repos cause this errors..how can i do for this ..

**Comment by christyuj** [comment]
this time i change my way as i know nil in ruby is not as same as it in objective-c so i just return a pathname but do not use the realpath...god bless please pass...

**Comment by neonichu** [comment]
@christyuj I still see two issues with this:
- Your test doesn't actually test anything and the BananaNoHeaderLib.framework is really incomplete
- The failures on Travis are caused by using the wrong ref for the cocoapods-integration-specs submodule — you shouldn't need to change this at all, so best to revert to whatever it was originally

**Comment by neonichu** [comment]
Since #3967 has been fixed on master, we can close this PR as well. Thanks for opening it, @christyuj :+1:

**Comment by christyuj** [comment]
thank you for neonichu's help ~! ^_^

**Comment by segiddins** [comment]
It's actually not fixed on master, I thought the linked issue was something else.

**Comment by segiddins** [comment]
Descoping from the 0.39 release due to lack of activity

**Comment by segiddins** [comment]
This is now in master.

**Pull request closed without merging**
