### PR TITLE
Track .def files as sources

### PR DESCRIPTION
**Pull request by dnkoutso**
We use `.def` files for sources in one of our projects and pods do not pick them up as source files.

`.def` is just a generic extension for files we process using the preprocessor, it’s C/C++ source code.

I know its a bit unique of usage but it seems harmless to track this extension also.

### CODE REVIEW

**Comment by segiddins** [comment]
Can you please add a CHANGELOG entry?

**Comment by dnkoutso** [comment]
:+1:

**Comment by dnkoutso** [comment]
Done.

**Comment by segiddins** [comment]
:+1:

**Comment by segiddins** [comment]
Anyone else care to review this?

**Comment by neonichu** [comment]
:+1:

**Comment by dnkoutso** [comment]
Thank you!

**Pull request merged**
