### PR TITLE
Make copy resources echoes always return true

### LINKED ISSUE #6595: Pods-<Target>-resources.sh echo commands generate output too large for Xcode
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

While this really is a Xcode bug, it is unlikely to be fixed any time soon, if ever, and thus CocoaPods needs to work around it.

## What did you do?

Build workspace

## What did you expect to happen?

Build succeeds

## What happened instead?

Pods-Target-resources.sh script fails with error due to `echo` on line 48:
```
error: Resource temporarily unavailable
Command /bin/sh failed with exit code 1
```
### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : cocoapods - https://github.com/cocoapods/cocoapods.git @ 6a6df6f01d48b769bb89bc9f7d26bbc312624740
               LPM - git@github.com:lonelyplanet/lpm-specs-ios.git @ 2a89500ce94755688ab621a4dc9a8ce5081dd063
               master - https://github.com/CocoaPods/Specs.git @ 782b74bf2f9c3c131e41a105785e914d046dfdbd
```

### Installation Source

```
Executable Path: /Users/alondon/.gems/bin/pod
```

### Plugins

```
cocoapods-deintegrate   : 1.0.1
cocoapods-plugins       : 1.0.0
cocoapods-search        : 1.0.0
cocoapods-sorted-search : 0.2.4
cocoapods-stats         : 1.0.0
cocoapods-trunk         : 1.1.2
cocoapods-try           : 1.1.0
```

## Project that demonstrates the issue

In any project using CocoaPods replace all `echo` commands that go to stdout in `Pods/Target Support Files/Pods-Target/Pods-Target-resources.sh` with:

```
echo `printf '=%.0s' {1..600}` 
```

Appending `|| true` to those lines works around the issue.

### PR DESCRIPTION
**Pull request by postmechanical**
Resolves #6595

### CODE REVIEW

**Comment by postmechanical** [comment]
@dnkoutso 🎬 2️⃣ 👀 🙏

**Comment by dnkoutso** [comment]
@louisdh didnt those changes to .xcodeproj make it into master from your PRs?

**Comment by louisdh** [comment]
@dnkoutso Which changes? Also: I'm confused, what does .xcodeproj have to do with this issue?

**Comment by dnkoutso** [comment]
@louisdh in the diff in this PR the bumped submodule version of integration specs includes some .xcodeproj changes in the integration specs. If I recall correctly those were due to the upgrades to xcodeproj for Xcode 8.2.1 and Xcode 8.3.

Sorry if I am adding to the confusion here, this PR is supposed to just change the `.sh` files.

**Comment by louisdh** [comment]
Ah yes, it seems, @postmechanical, that you started from 5d471d6e1a9290b8d3c74cdc726c3493673c33d9 (btw, it's recommended to make a new branch for a PR 🙂). Your master is 8 commits behind.

**Comment by postmechanical** [comment]
@louisdh yeah, I would have preferred to do it on a fix branch in the main repo rather than a fork but figured I wouldn't have perms.

**Comment by louisdh** [comment]
@postmechanical Why not on a "fix branch" in your fork?

**Comment by dnkoutso** [comment]
@postmechanical this is still not right for us to merge thats they the build is red.

**Comment by postmechanical** [comment]
@louisdh @dnkoutso Yep, I'll try and take another 🏃 at this.

**Comment by postmechanical** [comment]
@louisdh Do you want me to do a PR from a fix branch to `master` in my fork or from a fix branch in my fork to `master` in the main repo?

Also, curious to know why the specs are in a submodule? It seems counterintuitive to have the code and specs in different repos.

**Comment by postmechanical** [comment]
@dnkoutso @louisdh Another question, how can I do a CI build on a branch in my fork before opening a PR in the future?

**Comment by postmechanical** [comment]
I've blown away my fork and forked again, but I'm still getting the AFNetworking example build failure locally:

```
set -o pipefail && xcodebuild -workspace 'examples/AFNetworking Example/Examples.xcworkspace' -scheme 'AFNetworking Example' clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee $TMPDIR/xcode_raw.log | xcpretty --color --report junit --output $TMPDIR/xcode/results.xml
xcodebuild: error: Scheme AFNetworking Example is not currently configured for the test action.
```

**Comment by postmechanical** [comment]
When I clone the main CocoaPods repo fresh and run the AFNetworking example build I get the same failure as well.

**Pull request closed without merging**
