### PR TITLE
[CopyResourcesScript] Copy only the resources required for the current build configuration.

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/2391.

\c @kylef @mrackwitz

### CODE REVIEW

**Comment by segiddins** [comment]
The Travis failures are due to changes in the integration spec, which you can use to verify the fix actually works.

**Comment by mrackwitz** [comment]
@segiddins: For once, I added my feedback as commits, directly. Still had a local-only (:scream:) branch implementing the same feature.

**Comment by segiddins** [comment]
Good for me to merge?

**Comment by mrackwitz** [comment]
Sure :+1:

**Pull request merged**
