### PR TITLE
[FileAccessor] Take exclude_files into account for resource_bundles

### LINKED ISSUE #4065: exclude_files ignored for resource_bundles
As it seems ```exclude_files``` is ignored for ```resource_bundles```. Example:

    s.exclude_files = 'Some/resources/**/Tutorial*.png'
    s.resource_bundle = { 'someResources' => [ 'Some/resources/**/*.{png,lproj}' ] }

The problem [has been mentioned before] (https://github.com/CocoaPods/CocoaPods/issues/1393#issuecomment-26402612) i think but the above does not work as expected.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #4065.

- [x] Test
- [x] CHANGELOG

### CODE REVIEW

**Comment by kylef** [comment]
Didn't realise Circle CI was building without a circle.yml file, I've disabled it so this is now :green_apple:.

**Comment by kylef** [comment]
:+1: once we have tests.

**Comment by segiddins** [comment]
This should now be good to go!

**Comment by kylef** [comment]
:+1:

**Pull request merged**
