### PR TITLE
Move Installer target verification into the Xcode namespace

### PR DESCRIPTION
**Pull request by DanToml**
This PR moves Xcode specific parts of target verification and validation into the Xcode namespace and out of the Installer itself.

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
        
            1 Error
        
      </th>
     </tr>
  </thead>
  <tbody>
        <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! \nYou can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
    
    
  </tbody>
</table>
  

  

  



Here's an example of your CHANGELOG entry:

```markdown
* Move Installer target verification into the Xcode namespace 
  [DanToml](https://github.com/DanToml)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.




<p align="right" data-meta="generated_by_danger" data-base-commit="" data-head-commit="" >
  Generated by :no_entry_sign: <a href="https://github.com/danger/danger/">danger</a>
</p>

**Comment by segiddins** [comment]
👍🏻

**Comment by segiddins** [comment]
@DanToml what happened with this?

**Comment by orta** [comment]
Seems worth giving. look over, I don't see anything too contraversial

**Comment by DanToml** [comment]
@orta @segiddins oh this is actually ready to merge. I think it was :+1:'d just before I had a commit bit on this repo.

**Pull request merged**
