### PR TITLE
Clear out PRIVATE/PUBLIC_HEADERS_FOLDER_PATH

### LINKED ISSUE #4119: Archives broken in Xcode 7β6 by containing public pod headers
I'm getting "Generic Xcode archives" when archiving in Xcode 7 beta 6 and using cocoapods 0.39 beta 4. When inspecting the archive I've noticed that public headers from the pods are included in the archive.

screen shot 2015-09-02 at 18 35 18

If I manually go through the pods and move all the headers from public/private to project that makes the archive valid.

But I'm sure that's not the proper way. Am I missing something?

### PR DESCRIPTION
**Pull request by neonichu**
This fixes an issue with archiving introduced by changing header accessibility attributes.

Fixes #4119

- [x] Tests
- [x] Changelog

### CODE REVIEW

**Comment by segiddins** [comment]
Pretty sure this should only be done for the static lib case?

**Comment by neonichu** [comment]
@segiddins you're right, updated :+1:

**Comment by AliSoftware** [comment]
Had the issue of invalid archive being generated. I just tested this branch using a `Gemfile` and can confirm it fixed the issue!

**Comment by vipom** [comment]
I tested and it fixed the issue for me too :) :+1:

**Comment by SJApps** [comment]
Eagerly waiting for this fix to be merged and deployed to gem :)

**Comment by segiddins** [comment]
:+1: once tests and CHANGELOG are added, and don't forget to update the integration specs

**Comment by menkel** [comment]
:+1:

**Comment by julienphilbert** [comment]
👍

**Comment by segiddins** [comment]
This should now be good to merge!

**Comment by pontusm** [comment]
Any chance you will release a new beta soon? We are having problems with creating archives so this fix would be welcome. :)

**Comment by segiddins** [comment]
@pontusm we're not really on a fixed schedule, but there should be a new beta soon

**Comment by pontusm** [comment]
Ok thanks!

Do you know any workaround I could use for now? I'm having major problems with creating the archive... If I remove the header folder path /usr/local/lib from all pod projects and move all header files from Public to Project under Build Phases the archive fails with an rsync error. Not sure how to solve this...

rsync: mkdir "/Users/pontusm/Library/Developer/Xcode/DerivedData/Rapid2-fpvggibcggtnaugcksjdfealbhcc/Build/Intermediates/ArchiveIntermediates/Rapid2/InstallationBuildProductsLocation/usr/local/lib" failed: No such file or directory (2)

**Comment by segiddins** [comment]
@pontusm I believe there are open issues for that already, but this PR isn't the place to discuss it

**Comment by pontusm** [comment]
Yeah sorry, you are right.

**Pull request merged**
