### PR TITLE
[README] Made capitalization and wording consistent 🌈

### PR DESCRIPTION
**Pull request by charleshkang**
Thought I'd submit a small PR fixing the wording for the sake of consistency!

### CODE REVIEW

**Comment by segiddins** [comment]
👍

**Comment by charleshkang** [comment]
@segiddins This is my first PR for CocoaPods, but will this be merged onto `master` after a few people approve it? Or if it's not enough of a change to merge, I'll try and find something to work on 😀

**Comment by segiddins** [comment]
Was just waiting until CI had run :)

**Comment by orta** [comment]
No PR is too small 👍

**Pull request merged**
