### PR TITLE
Updates probot setting for stale

### LINKED ISSUE #6862: Stale bot not closing issues
### Stale bot not closing issues
Currently, probot doesn't close stale issues for stale labels that contain spaces. [#44](https://github.com/probot/stale/pull/44)

Your stale label: `s1:awaiting input`

If you change this to `s1:awaiting_input` or another label without spaces then update your `stale.yml`, you can reap the full benefit of probot. 

Just thought I'd let you know as we had to deal with it in another repo 😅

### PR DESCRIPTION
**Pull request by orta**
Fixes #6862 
/cc @DanToml

### CODE REVIEW

**Comment by DanToml** [comment]
@orta https://github.com/CocoaPods/shared/pull/9

**Comment by SD10** [comment]
Yes, change the label name on GitHub before merging. The name change will be applied to all the issues and probot will start working in ~24hrs after merge.

**Comment by dnkoutso** [comment]
is this needed?

**Comment by SD10** [comment]
@dnkoutso No. Probot has been fixed. This issue can be closed 👍

**Pull request closed without merging**
