### PR TITLE
Add the App Clip product symbol to the list of products that need embedding

### PR DESCRIPTION
**Pull request by igor-makarov**
An App Clip is a standalone app, therefore frameworks need to be embedded into it.

### CODE REVIEW

**Comment by igor-makarov** [comment]
@amorde @dnkoutso I'm not sure where to test this.

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Add the App Clip product symbol to the list of products that need embedding  
  [igor-makarov](https://github.com/igor-makarov)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by amorde** [comment]
Looks like this test covers this code path, albeit for only one of the types

https://github.com/CocoaPods/CocoaPods/blob/ca12d45c95cdfb391b40391a8fda39f6ad265704/spec/unit/installer/user_project_integrator/target_integrator_spec.rb#L162-L169

We should probably add the rest but for this PR adding a case for App Clips should suffice

**Comment by igor-makarov** [comment]
Added the test @amorde @dnkoutso

**Comment by zlata** [comment]
@igor-makarov I'm using 1.10.0.beta.1, but Embed Pods Frameworks build phase still missing for App Clip target. Should I add something in my podfile?

**Comment by igor-makarov** [comment]
@dnkoutso it seems that https://github.com/CocoaPods/Xcodeproj/pull/768 hasn't been released, so App Clips aren't working...

**Comment by dnkoutso** [comment]
@igor-makarov I will make a release with beta 2 of 1.10.

**Comment by mashaf** [comment]
@igor-makarov  The same problem with @zlata : `1.10.0.beta.1`, but there are no pods frameworks for AppClip target in its build folder. Should we wait for `1.10.0.beta.2` ?

**Comment by mnshukla95** [comment]
@dnkoutso - any idea on when beta 2 of 1.10 will be released?

**Comment by borut-t** [comment]
@igor-makarov, @dnkoutso when can we expect new release with App Clips support?

**Comment by NachoSoto** [comment]
Has anyone successfully submitted an App Clip with CocoaPods? 
I'm using the latest version `1.10.0` with `Xcode 12.2 beta 3`, this is my configuration:

- `Podfile`:
Screen Shot 2020-10-29 at 16 33 41

- `Clip` target:
Screen Shot 2020-10-29 at 16 34 17

- App target:
Screen Shot 2020-10-29 at 16 34 52

However, submitting a build results on this error:
Screen Shot 2020-10-29 at 16 36 25

I've tried everything, but I can't figure out what's missing. My other extensions (widget, watchOS, notification) are all configured in exactly the same manner.

**Comment by igor-makarov** [comment]
Is the app clip target nested in the app target in the Podfile?

**Comment by NachoSoto** [comment]
It's not. I don't have any of my targets nested... should it be?

**Comment by igor-makarov** [comment]
@NachoSoto I'm not sure it's related. What do you have in "Link with Libraries" build phase for each?

**Comment by NachoSoto** [comment]
I tried nesting the target and still got the same error on submission.
Here are my link with libraries phases:

App target:
Screen Shot 2020-11-02 at 09 09 38

Clip target:
Screen Shot 2020-11-02 at 09 09 53

**Comment by NachoSoto** [comment]
Any updates here? I'm still unable to use App Clips with CocoaPods.

**Comment by NachoSoto** [comment]
Still unable to get this working on Xcode 13
Screen Shot 2021-09-21 at 15 20 33

**Pull request merged**
