### PR TITLE
Fix xcfilelist support not working for project object version >= 46 & < 50

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! <br />
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Fix xcfilelist support not working for project object version >= 46 & < 50  
  [revolter](https://github.com/revolter)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dnkoutso** [comment]
Project object version 46 is 'Xcode 3.2'. Xcfilelists were introduced in Xcode 9.x. I do not think we want this change.

**Comment by revolter** [comment]
But I have Xcode 10.2 with object version 46.

**Comment by dnkoutso** [comment]
I do not think that means that you can use xcfilelists in earlier versions of Xcode. If CocoaPods write an xcfilelist it won't be used/parsed by Xcode < 9

**Comment by revolter** [comment]
I see. So there's no good way of knowing exactly when was this introduced?

Could we add support for [`.xcode-version`](https://github.com/fastlane/ci/blob/master/docs/xcode-version.md) files?

**Comment by dnkoutso** [comment]
We could `.xcode-version` but it would have to be carefully thought out. My recommendation is to write an RFC like this one https://github.com/CocoaPods/CocoaPods/issues/9099 to make a good case why it would be helpful to the project.

I am going to close this PR for now.

**Pull request closed without merging**
