### PR TITLE
Redefine FOUNDATION_EXPORT for C-only pods in umbrella header

### LINKED ISSUE #6024: C podspecs are still failing due to undefined FOUNDATION_EXPORT
Although #5844 partially fixed the issue, if you import a C pod into another C pod it still fails because of `FOUNDATION_EXPORT` not being defined.

```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif

#import "sqlite3.h"

FOUNDATION_EXPORT double SQLCipherVersionNumber;
FOUNDATION_EXPORT const unsigned char SQLCipherVersionString[];
```

`FOUNDATION_EXPORT` isn't defined unless you `#import <Foundation/Foundation.h>`, but if you import that, you're back where you started by including Obj-C in a C-only build target. I'll try to figure out another workaround.

`FOUNDATION_EXPORT` is defined in `<Foundation/NSObjCRuntime.h>`, as an alias to `FOUNDATION_EXTERN`, which does this:

```objc
#if defined(__cplusplus)
#define FOUNDATION_EXTERN extern "C"
#else
#define FOUNDATION_EXTERN extern
#endif
```

We could do something similar in the umbrella header:

```obj-c
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
```

I am working on a pull request that fixes this by the above method.

Specifically the failure happens when SQLCipher `"sqlcipher/sqlite3.h"` is included in `sqlfs.c`:

https://github.com/guardianproject/libsqlfs/blob/master/sqlfs.c#L54

### PR DESCRIPTION
**Pull request by chrisballinger**
Fixes #6024 

e.g.

```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif
```

### CODE REVIEW

**Comment by dnkoutso** [comment]
I am not a primary CocoaPods maintainer, but LGTM.

**Comment by chrisballinger** [comment]
@dnkoutso thanks :)

This change works for us over here. Maybe this will fix the issues you were seeing with C++?

**Comment by dnkoutso** [comment]
Can try it out!

**Comment by CocoaPodsBarista** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit yourself! 
You can find it at <a href="https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

Here's an example of your CHANGELOG entry:

```markdown
* Redefine FOUNDATION_EXPORT for C-only pods in umbrella header 
  [chrisballinger](https://github.com/chrisballinger)
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
```

*note*: There are two invisible spaces after the entry's text.


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dnkoutso** [comment]
This will need tests and a changelog entry

**Comment by chrisballinger** [comment]
@dnkoutso I tried to modify the existing tests but guess I didn't do it properly. Will try to fix and add changelog entry

**Comment by chrisballinger** [comment]
Ok I think I fixed it all and it should be ✅

**Comment by benasher44** [comment]
Looks good! Can you update cocoapods-integration-specs?

**Comment by chrisballinger** [comment]
Yeah sorry I missed those

**Comment by dnkoutso** [comment]
@chrisballinger I believe also the changelog entry must have two spaces in the first line. It looks like you have one.

**Comment by benasher44** [comment]
This looks good to me. This just needs to be updated with master, and it looks like there are some specs that need to be updated to account for the new content in the header.

**Comment by chrisballinger** [comment]
@benasher44 I fixed the integration tests here: https://github.com/CocoaPods/cocoapods-integration-specs/pull/88

I didn't point this PR to my `cocoapods-integration-specs` fork so those tests will fail in Travis, but they all pass on my machine.

**Comment by benasher44** [comment]
Oh sorry one small request. Can you actually rebase with master instead of merge? Sorry about that.

**Comment by chrisballinger** [comment]
@benasher44 I can def rebase/squash manually but perhaps you could do it faster via the new GitHub feature? https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by benasher44** [comment]
@chrisballinger only issue there is that tests aren't re-run before merging.

**Comment by chrisballinger** [comment]
@benasher44 Oh okay. Is it still ok that the integration tests don't pass because the submodule points to the upstream remote instead of my fork?

**Comment by chrisballinger** [comment]
@benasher44 Rebased

**Comment by benasher44** [comment]
@chrisballinger your cocoapods-integration-specs is merged. can you update the submodule pointer here?

**Comment by benasher44** [comment]
Thanks! Will merge once CI is green.

**Comment by benasher44** [comment]
Thanks!

**Review by BertsLifee — COMMENTED** [review]
when working with C-only pods in an umbrella header, you can adjust how certain functions or symbols are shared across your project by redefining the way they are declared in the header file. This gives you more control over how these elements are used and accessed in your codebase

**Pull request merged**
