### PR TITLE
Wrap platform warning message with quotes

### PR DESCRIPTION
**Pull request by dnkoutso**

### CODE REVIEW

**Comment by orta** [comment]
Well, there's a bug, looks like the spell checker is using the PR branch for it's settings which doesn't exist in that repo.

**Comment by orta** [comment]
Orrr, it's not expecting a fork, and is using the Danger repo

**Comment by orta** [comment]
It's the latter.

**Comment by orta** [comment]
OK, so, this is at least better. I started built being able to ignore certain files in spellchecking, maybe I missed something somewhere there.

**Comment by orta** [comment]
Alright 👍

**Comment by dnkoutso** [comment]
With https://github.com/CocoaPods/cocoapods-integration-specs/pull/120

**Comment by dnkoutso** [comment]
rebased, will merge on green.

**Pull request merged**
