### PR TITLE
[Analyzer] Dont create cycles when computing transitive dependencies

### LINKED ISSUE #4092: SystemStackError - stack level too deep (0.39.beta.1 only)
:rainbow: 
- I can successfully `pod install` with 0.38.2, but `pod _0.39.0.beta1_ install` gives me the following. 
- I can reproduce this on a brand new project.
- If I remove the targets, I do not get this issue.
- I've attached the verbose output - let me know if there's anything else you need.

As an aside, I came across this while trying to [fix this issue](http://stackoverflow.com/questions/32236929/class-appears-to-be-loaded-from-different-nsbundle-in-tests-after-updating-cocoa) - I'm happy to open another issue for that if that's appropriate.

<pre>
Adams-MacBook-Pro:Closeout Adam$ pod _0.39.0.beta.1_ install --verbose
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     e16ed07..3688092  master     -> origin/master
  Updating e16ed07..3688092
  Fast-forward
   Specs/Bond/4.0.0-alpha.3/Bond.podspec.json         | 39 +++++++++++++++
   .../2.3.3/CWStatusBarNotification.podspec.json     | 24 +++++++++
   .../UIViewController+Subcontrollers.podspec.json   | 23 +++++++++
   Specs/ZSAdditions/0.1.16/ZSAdditions.podspec.json  | 23 +++++++++
   .../3.0.0-beta-9/gujemsiossdk.podspec.json         | 58 ++++++++++++++++++++++
   Specs/podtest-ios/0.1.0/podtest-ios.podspec.json   | 25 ++++++++++
   6 files changed, 192 insertions(+)
   create mode 100644 Specs/Bond/4.0.0-alpha.3/Bond.podspec.json
   create mode 100644 Specs/CWStatusBarNotification/2.3.3/CWStatusBarNotification.podspec.json
   create mode 100644 Specs/UIViewController+Subcontrollers/0.0.2/UIViewController+Subcontrollers.podspec.json
   create mode 100644 Specs/ZSAdditions/0.1.16/ZSAdditions.podspec.json
   create mode 100644 Specs/gujemsiossdk/3.0.0-beta-9/gujemsiossdk.podspec.json
   create mode 100644 Specs/podtest-ios/0.1.0/podtest-ios.podspec.json

CocoaPods 0.39.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Closeout`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-CloseoutTests`: (``)

Finding Podfile changes
  - AviarySDK
  - BBBadgeBarButtonItem
  - CWStatusBarNotification
  - FlurrySDK
  - OHHTTPStubs
  - Reachability
  - RestKit
  - RestKit/Testing
  - SDWebImage
  - SSKeychain
  - TPKeyboardAvoiding
  - TSMessages

Resolving dependencies of `Podfile`
</pre>

### Command

```
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0.beta.1
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/Adam/.rvm/rubies/ruby-2.1.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3688092a20dea667e101f0e89e7f89d882b7ad58
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.6.0
cocoapods-trunk   : 0.6.2
cocoapods-try     : 0.5.0
```

### Podfile

```ruby
platform :ios, '8.0'

target 'Closeout', :exclusive => true do
    pod 'RestKit'
    pod 'SSKeychain'
    pod 'Reachability'
    pod 'AviarySDK'
    pod 'FlurrySDK'
    pod 'SDWebImage'
    pod 'CWStatusBarNotification'
    pod 'TSMessages'
    pod 'TPKeyboardAvoiding'
    pod 'BBBadgeBarButtonItem'
end

target 'CloseoutTests' do
    pod 'RestKit/Testing'
    pod 'OHHTTPStubs'
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-Closeout/Pods-Closeout-acknowledgements.plist', 'bridgit-ios/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
```

### Error

```
SystemStackError - stack level too deep
/Users/Adam/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.39.0.beta.1/lib/cocoapods/target/pod_target.rb:63
```

### PR DESCRIPTION
**Pull request by segiddins**
Fixes #4092.

- [x] Tests
  - [x] Cycles in the analyzer
  - [x] Setting the property when scoping
- [x] Changelog

### CODE REVIEW

**Comment by kylef** [comment]
Good start :ok_hand:

**Comment by segiddins** [comment]
Issue with this PR, installing RestKit:

### Stack
```
   CocoaPods : 0.39.0.beta.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F1112)
       Xcode : 6.2 (6C131e)
         Git : git version 2.4.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-srgpodspecs - ssh://git@bitbucket.org/rtsmb/srgpodspecs.git @ ff793e40ebcdc2179baf7d85a891bd53cc8c2118
               master - https://github.com/CocoaPods/Specs.git @ 9ad118351e54ac86b3b99fc8436bea13ee814df7
```
### Plugins
```
cocoapods-dependencies : 0.4.0
cocoapods-plugins      : 0.4.2
cocoapods-stats        : 0.6.1
cocoapods-trunk        : 0.6.3
cocoapods-try          : 0.5.1
```
### Podfile
```ruby
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
target :RestKit do
  platform :ios, '5.1.1'
  podspec
end
target :RestKitFramework do
  platform :osx, '10.7'
  podspec
end
def import_pods
  pod 'RestKit', :path => '.'
  pod 'RestKit/Testing', :path => '.'
  pod 'RestKit/Search', :path => '.'
  pod 'Specta', '0.2.1'
  pod 'OCMock', '2.2.4'
  pod 'OCHamcrest', '3.0.1'
  pod 'Expecta', '0.3.1'
  # Used for testing Value Transformer integration
  pod 'RKCLLocationValueTransformer', '~> 1.1.0'
end
target :ios do
  platform :ios, '5.1.1'
  link_with 'RestKitTests'
  import_pods
end
target :osx do
  platform :osx, '10.7'
  link_with 'RestKitFrameworkTests'
  import_pods
end
```
### Error
```
NoMethodError - undefined method `file_accessors' for #<Array:0x007f963b426070>
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:46:in `each'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:46:in `flat_map'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:46:in `generate'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:35:in `save_as'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer/target_installer/pod_target_installer.rb:167:in `create_xcconfig_file'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer/target_installer/pod_target_installer.rb:22:in `block in install!'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/user_interface.rb:140:in `message'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:603:in `block (2 levels) in install_libraries'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:600:in `each'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:600:in `block in install_libraries'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/user_interface.rb:140:in `message'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:599:in `install_libraries'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:156:in `block in generate_pods_project'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/user_interface.rb:59:in `section'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:111:in `install!'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/command/project.rb:101:in `run'
/Users/0xced/Projects/Rainforest/CLAide/lib/claide/command.rb:312:in `run'
/Users/0xced/Projects/CocoaPods/CocoaPods/lib/cocoapods/command.rb:48:in `run'
/Users/0xced/Projects/CocoaPods/CocoaPods/bin/pod:44:in `<main>'
```

**Comment by segiddins** [comment]
Please review @mrackwitz, this should be ready to merge.

**Comment by kylef** [comment]
:+1:

**Comment by neonichu** [comment]
awesome :tada:

**Pull request merged**
