### PR TITLE
[Test Specs] Use external specs for tests

### LINKED ISSUE #3642: Move `spec/fixtures/spec-repos/test_repo` to separate repository
### How

* [x] Come up with a more self-explanatory name than `test_repo` (lives alongside the `master` repo, which is named `Specs`)
* [x] Create a repository on GitHub in the CocoaPods organization
* [x] Use `git filter-branch` on a fresh clone to extract the history to a new repository
* [x] Include the new repository as submodule

### Why

It can be used as a valid spec repo in our tests without mocking. This makes it easier to test specific dependency graphs.

### PR DESCRIPTION
**Pull request by nwest**
Closes #3642.

I kept the folder named `test_repo` because many of the specs are coupled to it. This would be a good refactor later on, though.

### CODE REVIEW

**Comment by segiddins** [comment]
👍

**Comment by segiddins** [comment]
@nwest there are a few spec failures

**Comment by nwest** [comment]
There's still some weird stuff going on where tests are modifying the specs folder when they shouldn't be. This hopefully will get them passing again, though.

**Comment by nwest** [comment]
Back to 📗 !

**Pull request merged**
