### PR TITLE
Fix setting `swift_version` when deduplicate targets is turned off.

### PR DESCRIPTION
**Pull request by dnkoutso**

### CODE REVIEW

**Comment by dnkoutso** [comment]
We could consider a 1.9.3 for this...and some other fixes. WDYT?

**Comment by dnkoutso** [comment]
It does not seem pressing though as I think noone is using dedup false otherwise we would see those reports coming in thousands!

**Comment by dnkoutso** [comment]
ah yes will do!

**Comment by paulb777** [comment]
Thanks! And I don't know of a reason for this to drive a 1.9.3. I just stumbled across it while investigating another issue.

**Comment by dnkoutso** [comment]
Updated test. Works well, will merge on green.

**Comment by acecilia** [comment]
I experience the same issue as explained in https://github.com/CocoaPods/CocoaPods/pull/9688: 
```
NoMethodError - undefined method `empty?' for nil:NilClass
/Users/paulbeusterien/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/target_validator.rb:118:in `block in verify_swift_pods_swift_version'
```

I tested installing cocoapods from master (which includes this PR), and I still see the crash.

The trigger is the following code:

```
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '4.2' if s.swift_versions.empty?
  end
end
```

You can reproduce the crash by doing `pod install` on the following Podfile:
```
use_frameworks!
platform :ios, '11.0'

pod 'InputMask', '4.2.0'

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '4.2' if s.swift_versions.empty?
  end
end
```

**Comment by dnkoutso** [comment]
Please file a new issue and upload a sample app along with it so we can debug/diagnose if we have regressed or not handling something.

Your Podfile that you pasted also doesn't seem to specify the option that turn off deduplication which this bug was for.

**Comment by acecilia** [comment]
@dnkoutso 

> Your Podfile that you pasted also doesn't seem to specify the option that turn off deduplication which this bug was for.

Correct, thats why I mentioned it in this PR. I will open an issue then, thanks

**Pull request merged**
