### PR TITLE
Fix assetcatalog_generated_info.plist path in copy resources phase

### LINKED ISSUE #7590: Archiving produces info.plist without ApplicationProperties for the Swift project without use_frameworks!
# Report

## What did you do?
Archiving a project.

## What did you expect to happen?
Correct and ready to upload archive is expected.

## What happened instead?
"Generic Xcode Archive" is created, further investigation showed that ApplicationProperties are missed from the info.plist
Presumably, this is related to the pods which contain resource files.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fc43809d0fcb810b3f8fcf8de13f169bf69e7046
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'test' do
    pod 'FAQView', '~> 0.5.0'
end
```

## Project that demonstrates the issue
https://www.dropbox.com/s/uh6vhtujaox0pkl/CocoaPodsIssueTestProject.zip?dl=0

### PR DESCRIPTION
**Pull request by MaximeLM**
Fixes #7590 

Tested locally with the sample projects from #7590 , #7003 , #7511 , app icons still show.

I'm also making a PR for cocoapods-integration-specs.

### CODE REVIEW

**Comment by dnkoutso** [comment]
nice! thank you for taking care of this. I was going to do it as well.

Also thanks for verifying the other issue continues to work.

**Comment by dnkoutso** [comment]
Merged the integration specs PR, please change this one to point to the right repo and we can merge.

**Comment by dnkoutso** [comment]
@MaximeLM this is because the integration specs this PR points to includes the ones from this PR https://github.com/CocoaPods/CocoaPods/pull/7610

**Comment by dnkoutso** [comment]
@MaximeLM let me land the other PR then this should go green. It might be a few days though. Do not worry though this will make it to 1.5.1

**Comment by MaximeLM** [comment]
@dnkoutso ok, thanks!

**Comment by dnkoutso** [comment]
@MaximeLM the other PR is merged can you rebase yours ?

**Comment by MaximeLM** [comment]
@dnkoutso done!

**Comment by dnkoutso** [comment]
@MaximeLM thank you!

**Pull request merged**
