### PR TITLE
Greenify success message

### LINKED ISSUE #5713: Green-ify Successful pod installation ?
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

*NOTE* First brought this issue up in Cocoapods Mac app: https://github.com/CocoaPods/CocoaPods-app/issues/354

Love cocoa pods, longtime user since its first release (back when it was still in MacRuby ;) ). One little thing that I think would be a nice to have. Would it be possible to have the very last line's text color in green? I find myself not being a 100% sure whenever i'm looking at the log. This is what i'm referring to:

screen shot 2016-08-02 at 12 33 05 pm

Maybe its just me but would be great to have: "Pod installation complete! There are 9 dependencies from the Podfile and 11 total pods installed." in green. Maybe I'm just getting old :)

More than happy to submit a PR if ppl are cool with the suggestion.

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
I expected the successful installation message to be in green:  "Pod installation complete! There are 9 dependencies from the Podfile and 11 total pods installed."

## What happened instead?

ℹ Please replace this with of what happened instead.  
The Pod installation line was in plain text color (white for command line and and black for the mac app)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

### PR DESCRIPTION
**Pull request by schayes04**
Fixes #5713

### CODE REVIEW

**Comment by orta** [comment]
Nice one 👍

**Comment by benasher44** [comment]
Looks good! The only thing that looks like is left to be done here is run `bundle exec rake spec:rebuild_integration_fixtures` to start fixing the test failures. Once you do that, you'll have changes in the  `specs/cocoapods-integration-specs` submodule. You can then go ahead and open a PR to have those merged (on CocoaPods/cocoapods-integration-specs). Once that's done, you can update the submodule pointer in this PR, and then this should be ready to merge!

**Comment by schayes04** [comment]
Ok thanks for pointing me in the right direction!

**Comment by schayes04** [comment]
Updated, not sure if I did the submodule pointer correctly. Let me know if I need to do anything else.

**Comment by benasher44** [comment]
@schayes04 it looks like you updated the submodule ref correctly, but you'll also need to update the .gitmodules file to point at your repo at least temporarily so Travis can give the 👍. Once the submodule repo is merged, that change can be undone.

**Comment by benasher44** [comment]
Travis is looking better! You just have to fix some rubocop failures now. You can see them by doing `bundle exec rake rubocop`

**Comment by schayes04** [comment]
@benasher44 Thanks for the help... seems like I'm getting closer. Looks like it passed when I removed

`-BUNDLED WITH		-   1.12.5`

from the Gemfile but I reverted it since I didn't think I should be changing that.

**Comment by benasher44** [comment]
@schayes04 something similar just happened to me in another PR. I restarted mine, and then it worked fine. So, I've restarted the build here as well.

**Comment by schayes04** [comment]
@benasher44 closer... now 2/3

**Comment by benasher44** [comment]
@schayes04. I think we can chock up 1/3 to flakinesss. I've merged your submodule change. Can you undo your .gitmodules change and update your submodule pointer to point at the merged commit?

**Comment by schayes04** [comment]
@benasher44 good to go!

**Pull request merged**
